# syntax=docker/dockerfile:1.7

ARG TARGETOS=linux
ARG TARGETARCH

FROM alpine:3.21 AS binary

ARG TARGETOS
ARG TARGETARCH

RUN --mount=type=bind,source=dist,target=/dist,readonly \
  cp "/dist/${TARGETOS}-${TARGETARCH}/git-plus" /git-plus

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=binary /git-plus /git-plus

ENV PORT=8080

EXPOSE 8080

ENTRYPOINT ["/git-plus"]
