// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitplus/config/v1/config.proto

package configv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ImSingee/git-plus/pkg/rpc/gitplus/config/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "gitplus.config.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServicePingProcedure is the fully-qualified name of the ConfigService's Ping RPC.
	ConfigServicePingProcedure = "/gitplus.config.v1.ConfigService/Ping"
	// ConfigServiceCheckConfigProcedure is the fully-qualified name of the ConfigService's CheckConfig
	// RPC.
	ConfigServiceCheckConfigProcedure = "/gitplus.config.v1.ConfigService/CheckConfig"
	// ConfigServiceCheckSourceConfigProcedure is the fully-qualified name of the ConfigService's
	// CheckSourceConfig RPC.
	ConfigServiceCheckSourceConfigProcedure = "/gitplus.config.v1.ConfigService/CheckSourceConfig"
	// ConfigServiceGetConfigProcedure is the fully-qualified name of the ConfigService's GetConfig RPC.
	ConfigServiceGetConfigProcedure = "/gitplus.config.v1.ConfigService/GetConfig"
	// ConfigServiceUpdateConfigProcedure is the fully-qualified name of the ConfigService's
	// UpdateConfig RPC.
	ConfigServiceUpdateConfigProcedure = "/gitplus.config.v1.ConfigService/UpdateConfig"
	// ConfigServiceCreateSourceProcedure is the fully-qualified name of the ConfigService's
	// CreateSource RPC.
	ConfigServiceCreateSourceProcedure = "/gitplus.config.v1.ConfigService/CreateSource"
	// ConfigServiceUpdateSourceProcedure is the fully-qualified name of the ConfigService's
	// UpdateSource RPC.
	ConfigServiceUpdateSourceProcedure = "/gitplus.config.v1.ConfigService/UpdateSource"
	// ConfigServiceReplaceSourceTokenProcedure is the fully-qualified name of the ConfigService's
	// ReplaceSourceToken RPC.
	ConfigServiceReplaceSourceTokenProcedure = "/gitplus.config.v1.ConfigService/ReplaceSourceToken"
	// ConfigServiceDeleteSourceProcedure is the fully-qualified name of the ConfigService's
	// DeleteSource RPC.
	ConfigServiceDeleteSourceProcedure = "/gitplus.config.v1.ConfigService/DeleteSource"
)

// ConfigServiceClient is a client for the gitplus.config.v1.ConfigService service.
type ConfigServiceClient interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	CheckConfig(context.Context, *connect.Request[v1.CheckConfigRequest]) (*connect.Response[v1.CheckConfigResponse], error)
	CheckSourceConfig(context.Context, *connect.Request[v1.CheckSourceConfigRequest]) (*connect.Response[v1.CheckSourceConfigResponse], error)
	GetConfig(context.Context, *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error)
	UpdateConfig(context.Context, *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error)
	CreateSource(context.Context, *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error)
	UpdateSource(context.Context, *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error)
	ReplaceSourceToken(context.Context, *connect.Request[v1.ReplaceSourceTokenRequest]) (*connect.Response[v1.ReplaceSourceTokenResponse], error)
	DeleteSource(context.Context, *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error)
}

// NewConfigServiceClient constructs a client for the gitplus.config.v1.ConfigService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1.File_gitplus_config_v1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+ConfigServicePingProcedure,
			connect.WithSchema(configServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		checkConfig: connect.NewClient[v1.CheckConfigRequest, v1.CheckConfigResponse](
			httpClient,
			baseURL+ConfigServiceCheckConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("CheckConfig")),
			connect.WithClientOptions(opts...),
		),
		checkSourceConfig: connect.NewClient[v1.CheckSourceConfigRequest, v1.CheckSourceConfigResponse](
			httpClient,
			baseURL+ConfigServiceCheckSourceConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("CheckSourceConfig")),
			connect.WithClientOptions(opts...),
		),
		getConfig: connect.NewClient[v1.GetConfigRequest, v1.GetConfigResponse](
			httpClient,
			baseURL+ConfigServiceGetConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetConfig")),
			connect.WithClientOptions(opts...),
		),
		updateConfig: connect.NewClient[v1.UpdateConfigRequest, v1.UpdateConfigResponse](
			httpClient,
			baseURL+ConfigServiceUpdateConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateConfig")),
			connect.WithClientOptions(opts...),
		),
		createSource: connect.NewClient[v1.CreateSourceRequest, v1.CreateSourceResponse](
			httpClient,
			baseURL+ConfigServiceCreateSourceProcedure,
			connect.WithSchema(configServiceMethods.ByName("CreateSource")),
			connect.WithClientOptions(opts...),
		),
		updateSource: connect.NewClient[v1.UpdateSourceRequest, v1.UpdateSourceResponse](
			httpClient,
			baseURL+ConfigServiceUpdateSourceProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateSource")),
			connect.WithClientOptions(opts...),
		),
		replaceSourceToken: connect.NewClient[v1.ReplaceSourceTokenRequest, v1.ReplaceSourceTokenResponse](
			httpClient,
			baseURL+ConfigServiceReplaceSourceTokenProcedure,
			connect.WithSchema(configServiceMethods.ByName("ReplaceSourceToken")),
			connect.WithClientOptions(opts...),
		),
		deleteSource: connect.NewClient[v1.DeleteSourceRequest, v1.DeleteSourceResponse](
			httpClient,
			baseURL+ConfigServiceDeleteSourceProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteSource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	ping               *connect.Client[v1.PingRequest, v1.PingResponse]
	checkConfig        *connect.Client[v1.CheckConfigRequest, v1.CheckConfigResponse]
	checkSourceConfig  *connect.Client[v1.CheckSourceConfigRequest, v1.CheckSourceConfigResponse]
	getConfig          *connect.Client[v1.GetConfigRequest, v1.GetConfigResponse]
	updateConfig       *connect.Client[v1.UpdateConfigRequest, v1.UpdateConfigResponse]
	createSource       *connect.Client[v1.CreateSourceRequest, v1.CreateSourceResponse]
	updateSource       *connect.Client[v1.UpdateSourceRequest, v1.UpdateSourceResponse]
	replaceSourceToken *connect.Client[v1.ReplaceSourceTokenRequest, v1.ReplaceSourceTokenResponse]
	deleteSource       *connect.Client[v1.DeleteSourceRequest, v1.DeleteSourceResponse]
}

// Ping calls gitplus.config.v1.ConfigService.Ping.
func (c *configServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// CheckConfig calls gitplus.config.v1.ConfigService.CheckConfig.
func (c *configServiceClient) CheckConfig(ctx context.Context, req *connect.Request[v1.CheckConfigRequest]) (*connect.Response[v1.CheckConfigResponse], error) {
	return c.checkConfig.CallUnary(ctx, req)
}

// CheckSourceConfig calls gitplus.config.v1.ConfigService.CheckSourceConfig.
func (c *configServiceClient) CheckSourceConfig(ctx context.Context, req *connect.Request[v1.CheckSourceConfigRequest]) (*connect.Response[v1.CheckSourceConfigResponse], error) {
	return c.checkSourceConfig.CallUnary(ctx, req)
}

// GetConfig calls gitplus.config.v1.ConfigService.GetConfig.
func (c *configServiceClient) GetConfig(ctx context.Context, req *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error) {
	return c.getConfig.CallUnary(ctx, req)
}

// UpdateConfig calls gitplus.config.v1.ConfigService.UpdateConfig.
func (c *configServiceClient) UpdateConfig(ctx context.Context, req *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error) {
	return c.updateConfig.CallUnary(ctx, req)
}

// CreateSource calls gitplus.config.v1.ConfigService.CreateSource.
func (c *configServiceClient) CreateSource(ctx context.Context, req *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error) {
	return c.createSource.CallUnary(ctx, req)
}

// UpdateSource calls gitplus.config.v1.ConfigService.UpdateSource.
func (c *configServiceClient) UpdateSource(ctx context.Context, req *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error) {
	return c.updateSource.CallUnary(ctx, req)
}

// ReplaceSourceToken calls gitplus.config.v1.ConfigService.ReplaceSourceToken.
func (c *configServiceClient) ReplaceSourceToken(ctx context.Context, req *connect.Request[v1.ReplaceSourceTokenRequest]) (*connect.Response[v1.ReplaceSourceTokenResponse], error) {
	return c.replaceSourceToken.CallUnary(ctx, req)
}

// DeleteSource calls gitplus.config.v1.ConfigService.DeleteSource.
func (c *configServiceClient) DeleteSource(ctx context.Context, req *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error) {
	return c.deleteSource.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the gitplus.config.v1.ConfigService service.
type ConfigServiceHandler interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	CheckConfig(context.Context, *connect.Request[v1.CheckConfigRequest]) (*connect.Response[v1.CheckConfigResponse], error)
	CheckSourceConfig(context.Context, *connect.Request[v1.CheckSourceConfigRequest]) (*connect.Response[v1.CheckSourceConfigResponse], error)
	GetConfig(context.Context, *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error)
	UpdateConfig(context.Context, *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error)
	CreateSource(context.Context, *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error)
	UpdateSource(context.Context, *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error)
	ReplaceSourceToken(context.Context, *connect.Request[v1.ReplaceSourceTokenRequest]) (*connect.Response[v1.ReplaceSourceTokenResponse], error)
	DeleteSource(context.Context, *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1.File_gitplus_config_v1_config_proto.Services().ByName("ConfigService").Methods()
	configServicePingHandler := connect.NewUnaryHandler(
		ConfigServicePingProcedure,
		svc.Ping,
		connect.WithSchema(configServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceCheckConfigHandler := connect.NewUnaryHandler(
		ConfigServiceCheckConfigProcedure,
		svc.CheckConfig,
		connect.WithSchema(configServiceMethods.ByName("CheckConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceCheckSourceConfigHandler := connect.NewUnaryHandler(
		ConfigServiceCheckSourceConfigProcedure,
		svc.CheckSourceConfig,
		connect.WithSchema(configServiceMethods.ByName("CheckSourceConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetConfigHandler := connect.NewUnaryHandler(
		ConfigServiceGetConfigProcedure,
		svc.GetConfig,
		connect.WithSchema(configServiceMethods.ByName("GetConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateConfigHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateConfigProcedure,
		svc.UpdateConfig,
		connect.WithSchema(configServiceMethods.ByName("UpdateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceCreateSourceHandler := connect.NewUnaryHandler(
		ConfigServiceCreateSourceProcedure,
		svc.CreateSource,
		connect.WithSchema(configServiceMethods.ByName("CreateSource")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateSourceHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateSourceProcedure,
		svc.UpdateSource,
		connect.WithSchema(configServiceMethods.ByName("UpdateSource")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceReplaceSourceTokenHandler := connect.NewUnaryHandler(
		ConfigServiceReplaceSourceTokenProcedure,
		svc.ReplaceSourceToken,
		connect.WithSchema(configServiceMethods.ByName("ReplaceSourceToken")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteSourceHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteSourceProcedure,
		svc.DeleteSource,
		connect.WithSchema(configServiceMethods.ByName("DeleteSource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitplus.config.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServicePingProcedure:
			configServicePingHandler.ServeHTTP(w, r)
		case ConfigServiceCheckConfigProcedure:
			configServiceCheckConfigHandler.ServeHTTP(w, r)
		case ConfigServiceCheckSourceConfigProcedure:
			configServiceCheckSourceConfigHandler.ServeHTTP(w, r)
		case ConfigServiceGetConfigProcedure:
			configServiceGetConfigHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateConfigProcedure:
			configServiceUpdateConfigHandler.ServeHTTP(w, r)
		case ConfigServiceCreateSourceProcedure:
			configServiceCreateSourceHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateSourceProcedure:
			configServiceUpdateSourceHandler.ServeHTTP(w, r)
		case ConfigServiceReplaceSourceTokenProcedure:
			configServiceReplaceSourceTokenHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteSourceProcedure:
			configServiceDeleteSourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.Ping is not implemented"))
}

func (UnimplementedConfigServiceHandler) CheckConfig(context.Context, *connect.Request[v1.CheckConfigRequest]) (*connect.Response[v1.CheckConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.CheckConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) CheckSourceConfig(context.Context, *connect.Request[v1.CheckSourceConfigRequest]) (*connect.Response[v1.CheckSourceConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.CheckSourceConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetConfig(context.Context, *connect.Request[v1.GetConfigRequest]) (*connect.Response[v1.GetConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.GetConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateConfig(context.Context, *connect.Request[v1.UpdateConfigRequest]) (*connect.Response[v1.UpdateConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.UpdateConfig is not implemented"))
}

func (UnimplementedConfigServiceHandler) CreateSource(context.Context, *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.CreateSource is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateSource(context.Context, *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.UpdateSource is not implemented"))
}

func (UnimplementedConfigServiceHandler) ReplaceSourceToken(context.Context, *connect.Request[v1.ReplaceSourceTokenRequest]) (*connect.Response[v1.ReplaceSourceTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.ReplaceSourceToken is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteSource(context.Context, *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.config.v1.ConfigService.DeleteSource is not implemented"))
}
