// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitplus/cron/v1/cron.proto (package gitplus.cron.v1, edition 2023)
// option features.field_presence = EXPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_go_features, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gitplus/cron/v1/cron.proto.
 */
export const file_gitplus_cron_v1_cron: GenFile = /*@__PURE__*/
  fileDesc("ChpnaXRwbHVzL2Nyb24vdjEvY3Jvbi5wcm90bxIPZ2l0cGx1cy5jcm9uLnYxIp8BCgtDcm9uUnVudGltZRIPCgdlbmFibGVkGAEgASgIEgwKBGNyb24YAiABKAkSLgoKdXBkYXRlZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLQoJbmV4dF9ydW5zGAQgAygLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBISCgpsYXN0X2Vycm9yGAUgASgJIhcKFUdldENyb25SdW50aW1lUmVxdWVzdCJHChZHZXRDcm9uUnVudGltZVJlc3BvbnNlEi0KB3J1bnRpbWUYASABKAsyHC5naXRwbHVzLmNyb24udjEuQ3JvblJ1bnRpbWUiIQoRVXBkYXRlQ3JvblJlcXVlc3QSDAoEY3JvbhgBIAEoCSJDChJVcGRhdGVDcm9uUmVzcG9uc2USLQoHcnVudGltZRgBIAEoCzIcLmdpdHBsdXMuY3Jvbi52MS5Dcm9uUnVudGltZSITChFSZWxvYWRDcm9uUmVxdWVzdCJDChJSZWxvYWRDcm9uUmVzcG9uc2USLQoHcnVudGltZRgBIAEoCzIcLmdpdHBsdXMuY3Jvbi52MS5Dcm9uUnVudGltZTKeAgoLQ3JvblNlcnZpY2USYQoOR2V0Q3JvblJ1bnRpbWUSJi5naXRwbHVzLmNyb24udjEuR2V0Q3JvblJ1bnRpbWVSZXF1ZXN0GicuZ2l0cGx1cy5jcm9uLnYxLkdldENyb25SdW50aW1lUmVzcG9uc2USVQoKVXBkYXRlQ3JvbhIiLmdpdHBsdXMuY3Jvbi52MS5VcGRhdGVDcm9uUmVxdWVzdBojLmdpdHBsdXMuY3Jvbi52MS5VcGRhdGVDcm9uUmVzcG9uc2USVQoKUmVsb2FkQ3JvbhIiLmdpdHBsdXMuY3Jvbi52MS5SZWxvYWRDcm9uUmVxdWVzdBojLmdpdHBsdXMuY3Jvbi52MS5SZWxvYWRDcm9uUmVzcG9uc2VCxQEKE2NvbS5naXRwbHVzLmNyb24udjFCCUNyb25Qcm90b1ABWjtnaXRodWIuY29tL0ltU2luZ2VlL2dpdC1wbHVzL3BrZy9ycGMvZ2l0cGx1cy9jcm9uL3YxO2Nyb252MaICA0dDWKoCD0dpdHBsdXMuQ3Jvbi5WMcoCD0dpdHBsdXNcQ3JvblxWMeICG0dpdHBsdXNcQ3JvblxWMVxHUEJNZXRhZGF0YeoCEUdpdHBsdXM6OkNyb246OlYxkgMHCAHSPgIQAWIIZWRpdGlvbnNw6Ac", [file_google_protobuf_go_features, file_google_protobuf_timestamp]);

/**
 * @generated from message gitplus.cron.v1.CronRuntime
 */
export type CronRuntime = Message<"gitplus.cron.v1.CronRuntime"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: string cron = 2;
   */
  cron: string;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 3;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: repeated google.protobuf.Timestamp next_runs = 4;
   */
  nextRuns: Timestamp[];

  /**
   * @generated from field: string last_error = 5;
   */
  lastError: string;
};

/**
 * Describes the message gitplus.cron.v1.CronRuntime.
 * Use `create(CronRuntimeSchema)` to create a new message.
 */
export const CronRuntimeSchema: GenMessage<CronRuntime> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 0);

/**
 * @generated from message gitplus.cron.v1.GetCronRuntimeRequest
 */
export type GetCronRuntimeRequest = Message<"gitplus.cron.v1.GetCronRuntimeRequest"> & {
};

/**
 * Describes the message gitplus.cron.v1.GetCronRuntimeRequest.
 * Use `create(GetCronRuntimeRequestSchema)` to create a new message.
 */
export const GetCronRuntimeRequestSchema: GenMessage<GetCronRuntimeRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 1);

/**
 * @generated from message gitplus.cron.v1.GetCronRuntimeResponse
 */
export type GetCronRuntimeResponse = Message<"gitplus.cron.v1.GetCronRuntimeResponse"> & {
  /**
   * @generated from field: gitplus.cron.v1.CronRuntime runtime = 1;
   */
  runtime?: CronRuntime;
};

/**
 * Describes the message gitplus.cron.v1.GetCronRuntimeResponse.
 * Use `create(GetCronRuntimeResponseSchema)` to create a new message.
 */
export const GetCronRuntimeResponseSchema: GenMessage<GetCronRuntimeResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 2);

/**
 * @generated from message gitplus.cron.v1.UpdateCronRequest
 */
export type UpdateCronRequest = Message<"gitplus.cron.v1.UpdateCronRequest"> & {
  /**
   * @generated from field: string cron = 1;
   */
  cron: string;
};

/**
 * Describes the message gitplus.cron.v1.UpdateCronRequest.
 * Use `create(UpdateCronRequestSchema)` to create a new message.
 */
export const UpdateCronRequestSchema: GenMessage<UpdateCronRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 3);

/**
 * @generated from message gitplus.cron.v1.UpdateCronResponse
 */
export type UpdateCronResponse = Message<"gitplus.cron.v1.UpdateCronResponse"> & {
  /**
   * @generated from field: gitplus.cron.v1.CronRuntime runtime = 1;
   */
  runtime?: CronRuntime;
};

/**
 * Describes the message gitplus.cron.v1.UpdateCronResponse.
 * Use `create(UpdateCronResponseSchema)` to create a new message.
 */
export const UpdateCronResponseSchema: GenMessage<UpdateCronResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 4);

/**
 * @generated from message gitplus.cron.v1.ReloadCronRequest
 */
export type ReloadCronRequest = Message<"gitplus.cron.v1.ReloadCronRequest"> & {
};

/**
 * Describes the message gitplus.cron.v1.ReloadCronRequest.
 * Use `create(ReloadCronRequestSchema)` to create a new message.
 */
export const ReloadCronRequestSchema: GenMessage<ReloadCronRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 5);

/**
 * @generated from message gitplus.cron.v1.ReloadCronResponse
 */
export type ReloadCronResponse = Message<"gitplus.cron.v1.ReloadCronResponse"> & {
  /**
   * @generated from field: gitplus.cron.v1.CronRuntime runtime = 1;
   */
  runtime?: CronRuntime;
};

/**
 * Describes the message gitplus.cron.v1.ReloadCronResponse.
 * Use `create(ReloadCronResponseSchema)` to create a new message.
 */
export const ReloadCronResponseSchema: GenMessage<ReloadCronResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_cron_v1_cron, 6);

/**
 * @generated from service gitplus.cron.v1.CronService
 */
export const CronService: GenService<{
  /**
   * @generated from rpc gitplus.cron.v1.CronService.GetCronRuntime
   */
  getCronRuntime: {
    methodKind: "unary";
    input: typeof GetCronRuntimeRequestSchema;
    output: typeof GetCronRuntimeResponseSchema;
  },
  /**
   * @generated from rpc gitplus.cron.v1.CronService.UpdateCron
   */
  updateCron: {
    methodKind: "unary";
    input: typeof UpdateCronRequestSchema;
    output: typeof UpdateCronResponseSchema;
  },
  /**
   * @generated from rpc gitplus.cron.v1.CronService.ReloadCron
   */
  reloadCron: {
    methodKind: "unary";
    input: typeof ReloadCronRequestSchema;
    output: typeof ReloadCronResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gitplus_cron_v1_cron, 0);

