// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitplus/repo/v1/repo.proto

package repov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ImSingee/git-plus/pkg/rpc/gitplus/repo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RepoServiceName is the fully-qualified name of the RepoService service.
	RepoServiceName = "gitplus.repo.v1.RepoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RepoServiceListRepositoriesProcedure is the fully-qualified name of the RepoService's
	// ListRepositories RPC.
	RepoServiceListRepositoriesProcedure = "/gitplus.repo.v1.RepoService/ListRepositories"
	// RepoServiceGetRepositoryProcedure is the fully-qualified name of the RepoService's GetRepository
	// RPC.
	RepoServiceGetRepositoryProcedure = "/gitplus.repo.v1.RepoService/GetRepository"
	// RepoServiceStreamRepositoryDownloadProcedure is the fully-qualified name of the RepoService's
	// StreamRepositoryDownload RPC.
	RepoServiceStreamRepositoryDownloadProcedure = "/gitplus.repo.v1.RepoService/StreamRepositoryDownload"
	// RepoServiceListRefsProcedure is the fully-qualified name of the RepoService's ListRefs RPC.
	RepoServiceListRefsProcedure = "/gitplus.repo.v1.RepoService/ListRefs"
	// RepoServiceListRefChangesProcedure is the fully-qualified name of the RepoService's
	// ListRefChanges RPC.
	RepoServiceListRefChangesProcedure = "/gitplus.repo.v1.RepoService/ListRefChanges"
)

// RepoServiceClient is a client for the gitplus.repo.v1.RepoService service.
type RepoServiceClient interface {
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
	GetRepository(context.Context, *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error)
	StreamRepositoryDownload(context.Context, *connect.Request[v1.StreamRepositoryDownloadRequest]) (*connect.ServerStreamForClient[v1.StreamRepositoryDownloadResponse], error)
	ListRefs(context.Context, *connect.Request[v1.ListRefsRequest]) (*connect.Response[v1.ListRefsResponse], error)
	ListRefChanges(context.Context, *connect.Request[v1.ListRefChangesRequest]) (*connect.Response[v1.ListRefChangesResponse], error)
}

// NewRepoServiceClient constructs a client for the gitplus.repo.v1.RepoService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRepoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RepoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	repoServiceMethods := v1.File_gitplus_repo_v1_repo_proto.Services().ByName("RepoService").Methods()
	return &repoServiceClient{
		listRepositories: connect.NewClient[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse](
			httpClient,
			baseURL+RepoServiceListRepositoriesProcedure,
			connect.WithSchema(repoServiceMethods.ByName("ListRepositories")),
			connect.WithClientOptions(opts...),
		),
		getRepository: connect.NewClient[v1.GetRepositoryRequest, v1.GetRepositoryResponse](
			httpClient,
			baseURL+RepoServiceGetRepositoryProcedure,
			connect.WithSchema(repoServiceMethods.ByName("GetRepository")),
			connect.WithClientOptions(opts...),
		),
		streamRepositoryDownload: connect.NewClient[v1.StreamRepositoryDownloadRequest, v1.StreamRepositoryDownloadResponse](
			httpClient,
			baseURL+RepoServiceStreamRepositoryDownloadProcedure,
			connect.WithSchema(repoServiceMethods.ByName("StreamRepositoryDownload")),
			connect.WithClientOptions(opts...),
		),
		listRefs: connect.NewClient[v1.ListRefsRequest, v1.ListRefsResponse](
			httpClient,
			baseURL+RepoServiceListRefsProcedure,
			connect.WithSchema(repoServiceMethods.ByName("ListRefs")),
			connect.WithClientOptions(opts...),
		),
		listRefChanges: connect.NewClient[v1.ListRefChangesRequest, v1.ListRefChangesResponse](
			httpClient,
			baseURL+RepoServiceListRefChangesProcedure,
			connect.WithSchema(repoServiceMethods.ByName("ListRefChanges")),
			connect.WithClientOptions(opts...),
		),
	}
}

// repoServiceClient implements RepoServiceClient.
type repoServiceClient struct {
	listRepositories         *connect.Client[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse]
	getRepository            *connect.Client[v1.GetRepositoryRequest, v1.GetRepositoryResponse]
	streamRepositoryDownload *connect.Client[v1.StreamRepositoryDownloadRequest, v1.StreamRepositoryDownloadResponse]
	listRefs                 *connect.Client[v1.ListRefsRequest, v1.ListRefsResponse]
	listRefChanges           *connect.Client[v1.ListRefChangesRequest, v1.ListRefChangesResponse]
}

// ListRepositories calls gitplus.repo.v1.RepoService.ListRepositories.
func (c *repoServiceClient) ListRepositories(ctx context.Context, req *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return c.listRepositories.CallUnary(ctx, req)
}

// GetRepository calls gitplus.repo.v1.RepoService.GetRepository.
func (c *repoServiceClient) GetRepository(ctx context.Context, req *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error) {
	return c.getRepository.CallUnary(ctx, req)
}

// StreamRepositoryDownload calls gitplus.repo.v1.RepoService.StreamRepositoryDownload.
func (c *repoServiceClient) StreamRepositoryDownload(ctx context.Context, req *connect.Request[v1.StreamRepositoryDownloadRequest]) (*connect.ServerStreamForClient[v1.StreamRepositoryDownloadResponse], error) {
	return c.streamRepositoryDownload.CallServerStream(ctx, req)
}

// ListRefs calls gitplus.repo.v1.RepoService.ListRefs.
func (c *repoServiceClient) ListRefs(ctx context.Context, req *connect.Request[v1.ListRefsRequest]) (*connect.Response[v1.ListRefsResponse], error) {
	return c.listRefs.CallUnary(ctx, req)
}

// ListRefChanges calls gitplus.repo.v1.RepoService.ListRefChanges.
func (c *repoServiceClient) ListRefChanges(ctx context.Context, req *connect.Request[v1.ListRefChangesRequest]) (*connect.Response[v1.ListRefChangesResponse], error) {
	return c.listRefChanges.CallUnary(ctx, req)
}

// RepoServiceHandler is an implementation of the gitplus.repo.v1.RepoService service.
type RepoServiceHandler interface {
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
	GetRepository(context.Context, *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error)
	StreamRepositoryDownload(context.Context, *connect.Request[v1.StreamRepositoryDownloadRequest], *connect.ServerStream[v1.StreamRepositoryDownloadResponse]) error
	ListRefs(context.Context, *connect.Request[v1.ListRefsRequest]) (*connect.Response[v1.ListRefsResponse], error)
	ListRefChanges(context.Context, *connect.Request[v1.ListRefChangesRequest]) (*connect.Response[v1.ListRefChangesResponse], error)
}

// NewRepoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRepoServiceHandler(svc RepoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	repoServiceMethods := v1.File_gitplus_repo_v1_repo_proto.Services().ByName("RepoService").Methods()
	repoServiceListRepositoriesHandler := connect.NewUnaryHandler(
		RepoServiceListRepositoriesProcedure,
		svc.ListRepositories,
		connect.WithSchema(repoServiceMethods.ByName("ListRepositories")),
		connect.WithHandlerOptions(opts...),
	)
	repoServiceGetRepositoryHandler := connect.NewUnaryHandler(
		RepoServiceGetRepositoryProcedure,
		svc.GetRepository,
		connect.WithSchema(repoServiceMethods.ByName("GetRepository")),
		connect.WithHandlerOptions(opts...),
	)
	repoServiceStreamRepositoryDownloadHandler := connect.NewServerStreamHandler(
		RepoServiceStreamRepositoryDownloadProcedure,
		svc.StreamRepositoryDownload,
		connect.WithSchema(repoServiceMethods.ByName("StreamRepositoryDownload")),
		connect.WithHandlerOptions(opts...),
	)
	repoServiceListRefsHandler := connect.NewUnaryHandler(
		RepoServiceListRefsProcedure,
		svc.ListRefs,
		connect.WithSchema(repoServiceMethods.ByName("ListRefs")),
		connect.WithHandlerOptions(opts...),
	)
	repoServiceListRefChangesHandler := connect.NewUnaryHandler(
		RepoServiceListRefChangesProcedure,
		svc.ListRefChanges,
		connect.WithSchema(repoServiceMethods.ByName("ListRefChanges")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitplus.repo.v1.RepoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RepoServiceListRepositoriesProcedure:
			repoServiceListRepositoriesHandler.ServeHTTP(w, r)
		case RepoServiceGetRepositoryProcedure:
			repoServiceGetRepositoryHandler.ServeHTTP(w, r)
		case RepoServiceStreamRepositoryDownloadProcedure:
			repoServiceStreamRepositoryDownloadHandler.ServeHTTP(w, r)
		case RepoServiceListRefsProcedure:
			repoServiceListRefsHandler.ServeHTTP(w, r)
		case RepoServiceListRefChangesProcedure:
			repoServiceListRefChangesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRepoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRepoServiceHandler struct{}

func (UnimplementedRepoServiceHandler) ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.repo.v1.RepoService.ListRepositories is not implemented"))
}

func (UnimplementedRepoServiceHandler) GetRepository(context.Context, *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.repo.v1.RepoService.GetRepository is not implemented"))
}

func (UnimplementedRepoServiceHandler) StreamRepositoryDownload(context.Context, *connect.Request[v1.StreamRepositoryDownloadRequest], *connect.ServerStream[v1.StreamRepositoryDownloadResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.repo.v1.RepoService.StreamRepositoryDownload is not implemented"))
}

func (UnimplementedRepoServiceHandler) ListRefs(context.Context, *connect.Request[v1.ListRefsRequest]) (*connect.Response[v1.ListRefsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.repo.v1.RepoService.ListRefs is not implemented"))
}

func (UnimplementedRepoServiceHandler) ListRefChanges(context.Context, *connect.Request[v1.ListRefChangesRequest]) (*connect.Response[v1.ListRefChangesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.repo.v1.RepoService.ListRefChanges is not implemented"))
}
