// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitplus/repo/v1/repo.proto

package repov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SourceId      *string                `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Platform      *string                `protobuf:"bytes,3,opt,name=platform" json:"platform,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	FullName      *string                `protobuf:"bytes,5,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Owner         *string                `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
	HtmlUrl       *string                `protobuf:"bytes,8,opt,name=html_url,json=htmlUrl" json:"html_url,omitempty"`
	CloneUrl      *string                `protobuf:"bytes,9,opt,name=clone_url,json=cloneUrl" json:"clone_url,omitempty"`
	SshUrl        *string                `protobuf:"bytes,10,opt,name=ssh_url,json=sshUrl" json:"ssh_url,omitempty"`
	DefaultBranch *string                `protobuf:"bytes,11,opt,name=default_branch,json=defaultBranch" json:"default_branch,omitempty"`
	Visibility    *string                `protobuf:"bytes,12,opt,name=visibility" json:"visibility,omitempty"`
	IsPrivate     *bool                  `protobuf:"varint,13,opt,name=is_private,json=isPrivate" json:"is_private,omitempty"`
	IsFork        *bool                  `protobuf:"varint,14,opt,name=is_fork,json=isFork" json:"is_fork,omitempty"`
	IsArchived    *bool                  `protobuf:"varint,15,opt,name=is_archived,json=isArchived" json:"is_archived,omitempty"`
	Status        *string                `protobuf:"bytes,16,opt,name=status" json:"status,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_seen_at,json=lastSeenAt" json:"last_seen_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,20,opt,name=meta" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Repository) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *Repository) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Repository) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *Repository) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Repository) GetHtmlUrl() string {
	if x != nil && x.HtmlUrl != nil {
		return *x.HtmlUrl
	}
	return ""
}

func (x *Repository) GetCloneUrl() string {
	if x != nil && x.CloneUrl != nil {
		return *x.CloneUrl
	}
	return ""
}

func (x *Repository) GetSshUrl() string {
	if x != nil && x.SshUrl != nil {
		return *x.SshUrl
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil && x.DefaultBranch != nil {
		return *x.DefaultBranch
	}
	return ""
}

func (x *Repository) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *Repository) GetIsPrivate() bool {
	if x != nil && x.IsPrivate != nil {
		return *x.IsPrivate
	}
	return false
}

func (x *Repository) GetIsFork() bool {
	if x != nil && x.IsFork != nil {
		return *x.IsFork
	}
	return false
}

func (x *Repository) GetIsArchived() bool {
	if x != nil && x.IsArchived != nil {
		return *x.IsArchived
	}
	return false
}

func (x *Repository) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Repository) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Repository) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Repository) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Repository) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListRepositoriesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  *int32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	Search    *string                `protobuf:"bytes,3,opt,name=search" json:"search,omitempty"`
	SourceId  *string                `protobuf:"bytes,4,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	// Sort key combining field and direction.
	// Accepted values: "created_at_desc" (default), "created_at_asc",
	// "full_name_asc", "full_name_desc".
	Sort          *string `protobuf:"bytes,5,opt,name=sort" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{1}
}

func (x *ListRepositoriesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListRepositoriesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListRepositoriesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListRepositoriesRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *ListRepositoriesRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories" json:"repositories,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	TotalCount    *int32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{2}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *ListRepositoriesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *ListRepositoriesResponse) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

var File_gitplus_repo_v1_repo_proto protoreflect.FileDescriptor

const file_gitplus_repo_v1_repo_proto_rawDesc = "" +
	"\n" +
	"\x1agitplus/repo/v1/repo.proto\x12\x0fgitplus.repo.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x05\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x19\n" +
	"\bhtml_url\x18\b \x01(\tR\ahtmlUrl\x12\x1b\n" +
	"\tclone_url\x18\t \x01(\tR\bcloneUrl\x12\x17\n" +
	"\assh_url\x18\n" +
	" \x01(\tR\x06sshUrl\x12%\n" +
	"\x0edefault_branch\x18\v \x01(\tR\rdefaultBranch\x12\x1e\n" +
	"\n" +
	"visibility\x18\f \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"is_private\x18\r \x01(\bR\tisPrivate\x12\x17\n" +
	"\ais_fork\x18\x0e \x01(\bR\x06isFork\x12\x1f\n" +
	"\vis_archived\x18\x0f \x01(\bR\n" +
	"isArchived\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12<\n" +
	"\flast_seen_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x04meta\x18\x14 \x01(\v2\x17.google.protobuf.StructR\x04meta\"\xa9\x01\n" +
	"\x17ListRepositoriesRequest\x12&\n" +
	"\tpage_size\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\"\xa4\x01\n" +
	"\x18ListRepositoriesResponse\x12?\n" +
	"\frepositories\x18\x01 \x03(\v2\x1b.gitplus.repo.v1.RepositoryR\frepositories\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount2v\n" +
	"\vRepoService\x12g\n" +
	"\x10ListRepositories\x12(.gitplus.repo.v1.ListRepositoriesRequest\x1a).gitplus.repo.v1.ListRepositoriesResponseB\xc5\x01\n" +
	"\x13com.gitplus.repo.v1B\tRepoProtoP\x01Z;github.com/ImSingee/git-plus/pkg/rpc/gitplus/repo/v1;repov1\xa2\x02\x03GRX\xaa\x02\x0fGitplus.Repo.V1\xca\x02\x0fGitplus\\Repo\\V1\xe2\x02\x1bGitplus\\Repo\\V1\\GPBMetadata\xea\x02\x11Gitplus::Repo::V1\x92\x03\a\xd2>\x02\x10\x01\b\x01b\beditionsp\xe8\a"

var (
	file_gitplus_repo_v1_repo_proto_rawDescOnce sync.Once
	file_gitplus_repo_v1_repo_proto_rawDescData []byte
)

func file_gitplus_repo_v1_repo_proto_rawDescGZIP() []byte {
	file_gitplus_repo_v1_repo_proto_rawDescOnce.Do(func() {
		file_gitplus_repo_v1_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitplus_repo_v1_repo_proto_rawDesc), len(file_gitplus_repo_v1_repo_proto_rawDesc)))
	})
	return file_gitplus_repo_v1_repo_proto_rawDescData
}

var file_gitplus_repo_v1_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gitplus_repo_v1_repo_proto_goTypes = []any{
	(*Repository)(nil),               // 0: gitplus.repo.v1.Repository
	(*ListRepositoriesRequest)(nil),  // 1: gitplus.repo.v1.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 2: gitplus.repo.v1.ListRepositoriesResponse
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 4: google.protobuf.Struct
}
var file_gitplus_repo_v1_repo_proto_depIdxs = []int32{
	3, // 0: gitplus.repo.v1.Repository.last_seen_at:type_name -> google.protobuf.Timestamp
	3, // 1: gitplus.repo.v1.Repository.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: gitplus.repo.v1.Repository.updated_at:type_name -> google.protobuf.Timestamp
	4, // 3: gitplus.repo.v1.Repository.meta:type_name -> google.protobuf.Struct
	0, // 4: gitplus.repo.v1.ListRepositoriesResponse.repositories:type_name -> gitplus.repo.v1.Repository
	1, // 5: gitplus.repo.v1.RepoService.ListRepositories:input_type -> gitplus.repo.v1.ListRepositoriesRequest
	2, // 6: gitplus.repo.v1.RepoService.ListRepositories:output_type -> gitplus.repo.v1.ListRepositoriesResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gitplus_repo_v1_repo_proto_init() }
func file_gitplus_repo_v1_repo_proto_init() {
	if File_gitplus_repo_v1_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitplus_repo_v1_repo_proto_rawDesc), len(file_gitplus_repo_v1_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitplus_repo_v1_repo_proto_goTypes,
		DependencyIndexes: file_gitplus_repo_v1_repo_proto_depIdxs,
		MessageInfos:      file_gitplus_repo_v1_repo_proto_msgTypes,
	}.Build()
	File_gitplus_repo_v1_repo_proto = out.File
	file_gitplus_repo_v1_repo_proto_goTypes = nil
	file_gitplus_repo_v1_repo_proto_depIdxs = nil
}
