// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitplus/repo/v1/repo.proto

package repov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SourceId      *string                `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Platform      *string                `protobuf:"bytes,3,opt,name=platform" json:"platform,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	FullName      *string                `protobuf:"bytes,5,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Owner         *string                `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
	HtmlUrl       *string                `protobuf:"bytes,8,opt,name=html_url,json=htmlUrl" json:"html_url,omitempty"`
	CloneUrl      *string                `protobuf:"bytes,9,opt,name=clone_url,json=cloneUrl" json:"clone_url,omitempty"`
	SshUrl        *string                `protobuf:"bytes,10,opt,name=ssh_url,json=sshUrl" json:"ssh_url,omitempty"`
	DefaultBranch *string                `protobuf:"bytes,11,opt,name=default_branch,json=defaultBranch" json:"default_branch,omitempty"`
	Visibility    *string                `protobuf:"bytes,12,opt,name=visibility" json:"visibility,omitempty"`
	IsPrivate     *bool                  `protobuf:"varint,13,opt,name=is_private,json=isPrivate" json:"is_private,omitempty"`
	IsFork        *bool                  `protobuf:"varint,14,opt,name=is_fork,json=isFork" json:"is_fork,omitempty"`
	IsArchived    *bool                  `protobuf:"varint,15,opt,name=is_archived,json=isArchived" json:"is_archived,omitempty"`
	Status        *string                `protobuf:"bytes,16,opt,name=status" json:"status,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_seen_at,json=lastSeenAt" json:"last_seen_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,20,opt,name=meta" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Repository) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *Repository) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Repository) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *Repository) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Repository) GetHtmlUrl() string {
	if x != nil && x.HtmlUrl != nil {
		return *x.HtmlUrl
	}
	return ""
}

func (x *Repository) GetCloneUrl() string {
	if x != nil && x.CloneUrl != nil {
		return *x.CloneUrl
	}
	return ""
}

func (x *Repository) GetSshUrl() string {
	if x != nil && x.SshUrl != nil {
		return *x.SshUrl
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil && x.DefaultBranch != nil {
		return *x.DefaultBranch
	}
	return ""
}

func (x *Repository) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *Repository) GetIsPrivate() bool {
	if x != nil && x.IsPrivate != nil {
		return *x.IsPrivate
	}
	return false
}

func (x *Repository) GetIsFork() bool {
	if x != nil && x.IsFork != nil {
		return *x.IsFork
	}
	return false
}

func (x *Repository) GetIsArchived() bool {
	if x != nil && x.IsArchived != nil {
		return *x.IsArchived
	}
	return false
}

func (x *Repository) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Repository) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Repository) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Repository) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Repository) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListRepositoriesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  *int32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	Search    *string                `protobuf:"bytes,3,opt,name=search" json:"search,omitempty"`
	SourceId  *string                `protobuf:"bytes,4,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	// Sort key combining field and direction.
	// Accepted values: "created_at_desc" (default), "created_at_asc",
	// "name_asc", "name_desc".
	Sort          *string `protobuf:"bytes,5,opt,name=sort" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{1}
}

func (x *ListRepositoriesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListRepositoriesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListRepositoriesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListRepositoriesRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *ListRepositoriesRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories" json:"repositories,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	TotalCount    *int32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{2}
}

func (x *ListRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *ListRepositoriesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *ListRepositoriesResponse) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

type GetRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{3}
}

func (x *GetRepositoryRequest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type GetRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{4}
}

func (x *GetRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type ListRefsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RepoId *int64                 `protobuf:"varint,1,opt,name=repo_id,json=repoId" json:"repo_id,omitempty"`
	// Filter by ref kind: "head" for branches, "tag" for tags.
	RefKind *string `protobuf:"bytes,2,opt,name=ref_kind,json=refKind" json:"ref_kind,omitempty"`
	// If true, include deleted refs. Default is false (active only).
	IncludeDeleted *bool `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRefsRequest) Reset() {
	*x = ListRefsRequest{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefsRequest) ProtoMessage() {}

func (x *ListRefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefsRequest.ProtoReflect.Descriptor instead.
func (*ListRefsRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{5}
}

func (x *ListRefsRequest) GetRepoId() int64 {
	if x != nil && x.RepoId != nil {
		return *x.RepoId
	}
	return 0
}

func (x *ListRefsRequest) GetRefKind() string {
	if x != nil && x.RefKind != nil {
		return *x.RefKind
	}
	return ""
}

func (x *ListRefsRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

type ListRefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*RepoRef             `protobuf:"bytes,1,rep,name=refs" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefsResponse) Reset() {
	*x = ListRefsResponse{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefsResponse) ProtoMessage() {}

func (x *ListRefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefsResponse.ProtoReflect.Descriptor instead.
func (*ListRefsResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{6}
}

func (x *ListRefsResponse) GetRefs() []*RepoRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ListRefChangesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RepoId *int64                 `protobuf:"varint,1,opt,name=repo_id,json=repoId" json:"repo_id,omitempty"`
	// Optional: filter by ref name (exact match).
	RefName       *string `protobuf:"bytes,2,opt,name=ref_name,json=refName" json:"ref_name,omitempty"`
	PageSize      *int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken     *string `protobuf:"bytes,4,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefChangesRequest) Reset() {
	*x = ListRefChangesRequest{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefChangesRequest) ProtoMessage() {}

func (x *ListRefChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefChangesRequest.ProtoReflect.Descriptor instead.
func (*ListRefChangesRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{7}
}

func (x *ListRefChangesRequest) GetRepoId() int64 {
	if x != nil && x.RepoId != nil {
		return *x.RepoId
	}
	return 0
}

func (x *ListRefChangesRequest) GetRefName() string {
	if x != nil && x.RefName != nil {
		return *x.RefName
	}
	return ""
}

func (x *ListRefChangesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListRefChangesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListRefChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*RepoRefChange       `protobuf:"bytes,1,rep,name=changes" json:"changes,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	TotalCount    *int32                 `protobuf:"varint,3,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRefChangesResponse) Reset() {
	*x = ListRefChangesResponse{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRefChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefChangesResponse) ProtoMessage() {}

func (x *ListRefChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefChangesResponse.ProtoReflect.Descriptor instead.
func (*ListRefChangesResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{8}
}

func (x *ListRefChangesResponse) GetChanges() []*RepoRefChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ListRefChangesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *ListRefChangesResponse) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

type RepoRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	RefName        *string                `protobuf:"bytes,2,opt,name=ref_name,json=refName" json:"ref_name,omitempty"`
	RefKind        *string                `protobuf:"bytes,3,opt,name=ref_kind,json=refKind" json:"ref_kind,omitempty"`
	CurrentHash    *string                `protobuf:"bytes,4,opt,name=current_hash,json=currentHash" json:"current_hash,omitempty"`
	Status         *string                `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	ArchiveRefName *string                `protobuf:"bytes,6,opt,name=archive_ref_name,json=archiveRefName" json:"archive_ref_name,omitempty"`
	FirstSeenAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=first_seen_at,json=firstSeenAt" json:"first_seen_at,omitempty"`
	LastSeenAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen_at,json=lastSeenAt" json:"last_seen_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RepoRef) Reset() {
	*x = RepoRef{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRef) ProtoMessage() {}

func (x *RepoRef) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRef.ProtoReflect.Descriptor instead.
func (*RepoRef) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{9}
}

func (x *RepoRef) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RepoRef) GetRefName() string {
	if x != nil && x.RefName != nil {
		return *x.RefName
	}
	return ""
}

func (x *RepoRef) GetRefKind() string {
	if x != nil && x.RefKind != nil {
		return *x.RefKind
	}
	return ""
}

func (x *RepoRef) GetCurrentHash() string {
	if x != nil && x.CurrentHash != nil {
		return *x.CurrentHash
	}
	return ""
}

func (x *RepoRef) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *RepoRef) GetArchiveRefName() string {
	if x != nil && x.ArchiveRefName != nil {
		return *x.ArchiveRefName
	}
	return ""
}

func (x *RepoRef) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *RepoRef) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *RepoRef) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type RepoRefChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	RefName        *string                `protobuf:"bytes,2,opt,name=ref_name,json=refName" json:"ref_name,omitempty"`
	RefKind        *string                `protobuf:"bytes,3,opt,name=ref_kind,json=refKind" json:"ref_kind,omitempty"`
	Action         *string                `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	OldHash        *string                `protobuf:"bytes,5,opt,name=old_hash,json=oldHash" json:"old_hash,omitempty"`
	NewHash        *string                `protobuf:"bytes,6,opt,name=new_hash,json=newHash" json:"new_hash,omitempty"`
	ArchiveRefName *string                `protobuf:"bytes,7,opt,name=archive_ref_name,json=archiveRefName" json:"archive_ref_name,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RepoRefChange) Reset() {
	*x = RepoRefChange{}
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRefChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRefChange) ProtoMessage() {}

func (x *RepoRefChange) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_repo_v1_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRefChange.ProtoReflect.Descriptor instead.
func (*RepoRefChange) Descriptor() ([]byte, []int) {
	return file_gitplus_repo_v1_repo_proto_rawDescGZIP(), []int{10}
}

func (x *RepoRefChange) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RepoRefChange) GetRefName() string {
	if x != nil && x.RefName != nil {
		return *x.RefName
	}
	return ""
}

func (x *RepoRefChange) GetRefKind() string {
	if x != nil && x.RefKind != nil {
		return *x.RefKind
	}
	return ""
}

func (x *RepoRefChange) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *RepoRefChange) GetOldHash() string {
	if x != nil && x.OldHash != nil {
		return *x.OldHash
	}
	return ""
}

func (x *RepoRefChange) GetNewHash() string {
	if x != nil && x.NewHash != nil {
		return *x.NewHash
	}
	return ""
}

func (x *RepoRefChange) GetArchiveRefName() string {
	if x != nil && x.ArchiveRefName != nil {
		return *x.ArchiveRefName
	}
	return ""
}

func (x *RepoRefChange) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_gitplus_repo_v1_repo_proto protoreflect.FileDescriptor

const file_gitplus_repo_v1_repo_proto_rawDesc = "" +
	"\n" +
	"\x1agitplus/repo/v1/repo.proto\x12\x0fgitplus.repo.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x05\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x19\n" +
	"\bhtml_url\x18\b \x01(\tR\ahtmlUrl\x12\x1b\n" +
	"\tclone_url\x18\t \x01(\tR\bcloneUrl\x12\x17\n" +
	"\assh_url\x18\n" +
	" \x01(\tR\x06sshUrl\x12%\n" +
	"\x0edefault_branch\x18\v \x01(\tR\rdefaultBranch\x12\x1e\n" +
	"\n" +
	"visibility\x18\f \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"is_private\x18\r \x01(\bR\tisPrivate\x12\x17\n" +
	"\ais_fork\x18\x0e \x01(\bR\x06isFork\x12\x1f\n" +
	"\vis_archived\x18\x0f \x01(\bR\n" +
	"isArchived\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12<\n" +
	"\flast_seen_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x04meta\x18\x14 \x01(\v2\x17.google.protobuf.StructR\x04meta\"\xa9\x01\n" +
	"\x17ListRepositoriesRequest\x12&\n" +
	"\tpage_size\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\"\xa4\x01\n" +
	"\x18ListRepositoriesResponse\x12?\n" +
	"\frepositories\x18\x01 \x03(\v2\x1b.gitplus.repo.v1.RepositoryR\frepositories\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"&\n" +
	"\x14GetRepositoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"T\n" +
	"\x15GetRepositoryResponse\x12;\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x1b.gitplus.repo.v1.RepositoryR\n" +
	"repository\"\x80\x01\n" +
	"\x0fListRefsRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\x03R\x06repoId\x12+\n" +
	"\bref_kind\x18\x02 \x01(\tB\x10\xbaH\rr\vR\x04headR\x03tagR\arefKind\x12'\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bR\x0eincludeDeleted\"@\n" +
	"\x10ListRefsResponse\x12,\n" +
	"\x04refs\x18\x01 \x03(\v2\x18.gitplus.repo.v1.RepoRefR\x04refs\"\x92\x01\n" +
	"\x15ListRefChangesRequest\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\x03R\x06repoId\x12\x19\n" +
	"\bref_name\x18\x02 \x01(\tR\arefName\x12&\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x9b\x01\n" +
	"\x16ListRefChangesResponse\x128\n" +
	"\achanges\x18\x01 \x03(\v2\x1e.gitplus.repo.v1.RepoRefChangeR\achanges\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xed\x02\n" +
	"\aRepoRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bref_name\x18\x02 \x01(\tR\arefName\x12\x19\n" +
	"\bref_kind\x18\x03 \x01(\tR\arefKind\x12!\n" +
	"\fcurrent_hash\x18\x04 \x01(\tR\vcurrentHash\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12(\n" +
	"\x10archive_ref_name\x18\x06 \x01(\tR\x0earchiveRefName\x12>\n" +
	"\rfirst_seen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12<\n" +
	"\flast_seen_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x129\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x88\x02\n" +
	"\rRepoRefChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bref_name\x18\x02 \x01(\tR\arefName\x12\x19\n" +
	"\bref_kind\x18\x03 \x01(\tR\arefKind\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x19\n" +
	"\bold_hash\x18\x05 \x01(\tR\aoldHash\x12\x19\n" +
	"\bnew_hash\x18\x06 \x01(\tR\anewHash\x12(\n" +
	"\x10archive_ref_name\x18\a \x01(\tR\x0earchiveRefName\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x8a\x03\n" +
	"\vRepoService\x12g\n" +
	"\x10ListRepositories\x12(.gitplus.repo.v1.ListRepositoriesRequest\x1a).gitplus.repo.v1.ListRepositoriesResponse\x12^\n" +
	"\rGetRepository\x12%.gitplus.repo.v1.GetRepositoryRequest\x1a&.gitplus.repo.v1.GetRepositoryResponse\x12O\n" +
	"\bListRefs\x12 .gitplus.repo.v1.ListRefsRequest\x1a!.gitplus.repo.v1.ListRefsResponse\x12a\n" +
	"\x0eListRefChanges\x12&.gitplus.repo.v1.ListRefChangesRequest\x1a'.gitplus.repo.v1.ListRefChangesResponseB\xc5\x01\n" +
	"\x13com.gitplus.repo.v1B\tRepoProtoP\x01Z;github.com/ImSingee/git-plus/pkg/rpc/gitplus/repo/v1;repov1\xa2\x02\x03GRX\xaa\x02\x0fGitplus.Repo.V1\xca\x02\x0fGitplus\\Repo\\V1\xe2\x02\x1bGitplus\\Repo\\V1\\GPBMetadata\xea\x02\x11Gitplus::Repo::V1\x92\x03\a\xd2>\x02\x10\x01\b\x01b\beditionsp\xe8\a"

var (
	file_gitplus_repo_v1_repo_proto_rawDescOnce sync.Once
	file_gitplus_repo_v1_repo_proto_rawDescData []byte
)

func file_gitplus_repo_v1_repo_proto_rawDescGZIP() []byte {
	file_gitplus_repo_v1_repo_proto_rawDescOnce.Do(func() {
		file_gitplus_repo_v1_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitplus_repo_v1_repo_proto_rawDesc), len(file_gitplus_repo_v1_repo_proto_rawDesc)))
	})
	return file_gitplus_repo_v1_repo_proto_rawDescData
}

var file_gitplus_repo_v1_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gitplus_repo_v1_repo_proto_goTypes = []any{
	(*Repository)(nil),               // 0: gitplus.repo.v1.Repository
	(*ListRepositoriesRequest)(nil),  // 1: gitplus.repo.v1.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 2: gitplus.repo.v1.ListRepositoriesResponse
	(*GetRepositoryRequest)(nil),     // 3: gitplus.repo.v1.GetRepositoryRequest
	(*GetRepositoryResponse)(nil),    // 4: gitplus.repo.v1.GetRepositoryResponse
	(*ListRefsRequest)(nil),          // 5: gitplus.repo.v1.ListRefsRequest
	(*ListRefsResponse)(nil),         // 6: gitplus.repo.v1.ListRefsResponse
	(*ListRefChangesRequest)(nil),    // 7: gitplus.repo.v1.ListRefChangesRequest
	(*ListRefChangesResponse)(nil),   // 8: gitplus.repo.v1.ListRefChangesResponse
	(*RepoRef)(nil),                  // 9: gitplus.repo.v1.RepoRef
	(*RepoRefChange)(nil),            // 10: gitplus.repo.v1.RepoRefChange
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 12: google.protobuf.Struct
}
var file_gitplus_repo_v1_repo_proto_depIdxs = []int32{
	11, // 0: gitplus.repo.v1.Repository.last_seen_at:type_name -> google.protobuf.Timestamp
	11, // 1: gitplus.repo.v1.Repository.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: gitplus.repo.v1.Repository.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: gitplus.repo.v1.Repository.meta:type_name -> google.protobuf.Struct
	0,  // 4: gitplus.repo.v1.ListRepositoriesResponse.repositories:type_name -> gitplus.repo.v1.Repository
	0,  // 5: gitplus.repo.v1.GetRepositoryResponse.repository:type_name -> gitplus.repo.v1.Repository
	9,  // 6: gitplus.repo.v1.ListRefsResponse.refs:type_name -> gitplus.repo.v1.RepoRef
	10, // 7: gitplus.repo.v1.ListRefChangesResponse.changes:type_name -> gitplus.repo.v1.RepoRefChange
	11, // 8: gitplus.repo.v1.RepoRef.first_seen_at:type_name -> google.protobuf.Timestamp
	11, // 9: gitplus.repo.v1.RepoRef.last_seen_at:type_name -> google.protobuf.Timestamp
	11, // 10: gitplus.repo.v1.RepoRef.deleted_at:type_name -> google.protobuf.Timestamp
	11, // 11: gitplus.repo.v1.RepoRefChange.created_at:type_name -> google.protobuf.Timestamp
	1,  // 12: gitplus.repo.v1.RepoService.ListRepositories:input_type -> gitplus.repo.v1.ListRepositoriesRequest
	3,  // 13: gitplus.repo.v1.RepoService.GetRepository:input_type -> gitplus.repo.v1.GetRepositoryRequest
	5,  // 14: gitplus.repo.v1.RepoService.ListRefs:input_type -> gitplus.repo.v1.ListRefsRequest
	7,  // 15: gitplus.repo.v1.RepoService.ListRefChanges:input_type -> gitplus.repo.v1.ListRefChangesRequest
	2,  // 16: gitplus.repo.v1.RepoService.ListRepositories:output_type -> gitplus.repo.v1.ListRepositoriesResponse
	4,  // 17: gitplus.repo.v1.RepoService.GetRepository:output_type -> gitplus.repo.v1.GetRepositoryResponse
	6,  // 18: gitplus.repo.v1.RepoService.ListRefs:output_type -> gitplus.repo.v1.ListRefsResponse
	8,  // 19: gitplus.repo.v1.RepoService.ListRefChanges:output_type -> gitplus.repo.v1.ListRefChangesResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gitplus_repo_v1_repo_proto_init() }
func file_gitplus_repo_v1_repo_proto_init() {
	if File_gitplus_repo_v1_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitplus_repo_v1_repo_proto_rawDesc), len(file_gitplus_repo_v1_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitplus_repo_v1_repo_proto_goTypes,
		DependencyIndexes: file_gitplus_repo_v1_repo_proto_depIdxs,
		MessageInfos:      file_gitplus_repo_v1_repo_proto_msgTypes,
	}.Build()
	File_gitplus_repo_v1_repo_proto = out.File
	file_gitplus_repo_v1_repo_proto_goTypes = nil
	file_gitplus_repo_v1_repo_proto_depIdxs = nil
}
