// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AppMetum struct {
	Key   string
	Value string
}

type Repo struct {
	ID            int64
	SourceID      string
	Platform      string
	RefID         string
	Status        string
	Name          string
	FullName      string
	Owner         string
	Description   sql.NullString
	HtmlUrl       sql.NullString
	CloneUrl      sql.NullString
	SshUrl        sql.NullString
	DefaultBranch sql.NullString
	Visibility    sql.NullString
	IsPrivate     int64
	IsFork        int64
	IsArchived    int64
	Origin        string
	Meta          string
	LastSeenAt    string
	DisabledAt    sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type TaskRun struct {
	TaskID               string
	ParentTaskID         sql.NullString
	JobID                string
	JobType              string
	Name                 string
	ArgsJson             sql.NullString
	Status               string
	CreatedAt            string
	StartedAt            string
	FinishedAt           sql.NullString
	ErrorMessage         sql.NullString
	LastProgressSummary  sql.NullString
	LastProgressMetaJson sql.NullString
	UpdatedAt            string
}

type TaskRunLog struct {
	ID           int64
	TaskID       string
	EventType    string
	Summary      sql.NullString
	MetaJson     sql.NullString
	ErrorMessage sql.NullString
	CreatedAt    string
}
