// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countRepoRefChanges = `-- name: CountRepoRefChanges :one
SELECT COUNT(1)
FROM repo_ref_changes
WHERE repo_id = ?1
  AND (?2 IS NULL OR ref_name = ?2)
`

type CountRepoRefChangesParams struct {
	RepoID  int64
	Column2 interface{}
}

func (q *Queries) CountRepoRefChanges(ctx context.Context, arg CountRepoRefChangesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepoRefChanges, arg.RepoID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReposFiltered = `-- name: CountReposFiltered :one
SELECT COUNT(1)
FROM repos
WHERE (?1 IS NULL OR source_id = ?1)
  AND (?2 IS NULL OR (full_name LIKE '%' || ?2 || '%' OR description LIKE '%' || ?2 || '%'))
`

type CountReposFilteredParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) CountReposFiltered(ctx context.Context, arg CountReposFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReposFiltered, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepo = `-- name: CreateRepo :exec
INSERT INTO repos (
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22
)
`

type CreateRepoParams struct {
	SourceID      string
	Platform      string
	RefID         string
	Status        string
	Name          string
	FullName      string
	Owner         string
	Description   sql.NullString
	HtmlUrl       sql.NullString
	CloneUrl      sql.NullString
	SshUrl        sql.NullString
	DefaultBranch sql.NullString
	Visibility    sql.NullString
	IsPrivate     int64
	IsFork        int64
	IsArchived    int64
	Origin        string
	Meta          string
	LastSeenAt    string
	DisabledAt    sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) error {
	_, err := q.db.ExecContext(ctx, createRepo,
		arg.SourceID,
		arg.Platform,
		arg.RefID,
		arg.Status,
		arg.Name,
		arg.FullName,
		arg.Owner,
		arg.Description,
		arg.HtmlUrl,
		arg.CloneUrl,
		arg.SshUrl,
		arg.DefaultBranch,
		arg.Visibility,
		arg.IsPrivate,
		arg.IsFork,
		arg.IsArchived,
		arg.Origin,
		arg.Meta,
		arg.LastSeenAt,
		arg.DisabledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getRepoById = `-- name: GetRepoById :one
SELECT
  id, source_id, platform, ref_id, status, name, full_name, owner,
  description, html_url, clone_url, ssh_url, default_branch, visibility,
  is_private, is_fork, is_archived, origin, meta, last_seen_at,
  disabled_at, created_at, updated_at
FROM repos
WHERE id = ?1
`

func (q *Queries) GetRepoById(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoById, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Platform,
		&i.RefID,
		&i.Status,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.Description,
		&i.HtmlUrl,
		&i.CloneUrl,
		&i.SshUrl,
		&i.DefaultBranch,
		&i.Visibility,
		&i.IsPrivate,
		&i.IsFork,
		&i.IsArchived,
		&i.Origin,
		&i.Meta,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveReposForSource = `-- name: ListActiveReposForSource :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE source_id = ?1
  AND status = 'active'
ORDER BY id
`

func (q *Queries) ListActiveReposForSource(ctx context.Context, sourceID string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReposForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoRefChangesFiltered = `-- name: ListRepoRefChangesFiltered :many
SELECT
  id, repo_id, task_run_id, ref_name, ref_kind, action,
  old_hash, new_hash, archive_ref_name, created_at
FROM repo_ref_changes
WHERE repo_id = ?1
  AND (?2 IS NULL OR ref_name = ?2)
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?4
`

type ListRepoRefChangesFilteredParams struct {
	RepoID  int64
	Column2 interface{}
	Limit   int64
	Offset  int64
}

func (q *Queries) ListRepoRefChangesFiltered(ctx context.Context, arg ListRepoRefChangesFilteredParams) ([]RepoRefChange, error) {
	rows, err := q.db.QueryContext(ctx, listRepoRefChangesFiltered,
		arg.RepoID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoRefChange
	for rows.Next() {
		var i RepoRefChange
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TaskRunID,
			&i.RefName,
			&i.RefKind,
			&i.Action,
			&i.OldHash,
			&i.NewHash,
			&i.ArchiveRefName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoRefs = `-- name: ListRepoRefs :many
SELECT
  id, repo_id, ref_name, ref_kind, current_hash, status,
  archive_ref_name, first_seen_at, last_seen_at, last_hash_updated_at, deleted_at,
  created_at, updated_at
FROM repo_refs_current
WHERE repo_id = ?1
  AND ref_kind = ?2
  AND (?3 = 1 OR status <> 'deleted')
ORDER BY ref_name
`

type ListRepoRefsParams struct {
	RepoID  int64
	RefKind string
	Column3 interface{}
}

func (q *Queries) ListRepoRefs(ctx context.Context, arg ListRepoRefsParams) ([]RepoRefsCurrent, error) {
	rows, err := q.db.QueryContext(ctx, listRepoRefs, arg.RepoID, arg.RefKind, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoRefsCurrent
	for rows.Next() {
		var i RepoRefsCurrent
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RefName,
			&i.RefKind,
			&i.CurrentHash,
			&i.Status,
			&i.ArchiveRefName,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastHashUpdatedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposFilteredCreatedAtAsc = `-- name: ListReposFilteredCreatedAtAsc :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE (
    ?1 IS NULL
    OR repos.source_id = ?1
  )
  AND (
    ?2 IS NULL
    OR (
      repos.full_name LIKE '%' || ?2 || '%'
      OR repos.description LIKE '%' || ?2 || '%'
    )
  )
ORDER BY repos.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListReposFilteredCreatedAtAscParams struct {
	SourceID interface{}
	Search   interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListReposFilteredCreatedAtAsc(ctx context.Context, arg ListReposFilteredCreatedAtAscParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposFilteredCreatedAtAsc,
		arg.SourceID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposFilteredCreatedAtDesc = `-- name: ListReposFilteredCreatedAtDesc :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE (
    ?1 IS NULL
    OR repos.source_id = ?1
  )
  AND (
    ?2 IS NULL
    OR (
      repos.full_name LIKE '%' || ?2 || '%'
      OR repos.description LIKE '%' || ?2 || '%'
    )
  )
ORDER BY repos.created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListReposFilteredCreatedAtDescParams struct {
	SourceID interface{}
	Search   interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListReposFilteredCreatedAtDesc(ctx context.Context, arg ListReposFilteredCreatedAtDescParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposFilteredCreatedAtDesc,
		arg.SourceID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposFilteredNameAsc = `-- name: ListReposFilteredNameAsc :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE (
    ?1 IS NULL
    OR repos.source_id = ?1
  )
  AND (
    ?2 IS NULL
    OR (
      repos.full_name LIKE '%' || ?2 || '%'
      OR repos.description LIKE '%' || ?2 || '%'
    )
  )
ORDER BY repos.name ASC
LIMIT ?4 OFFSET ?3
`

type ListReposFilteredNameAscParams struct {
	SourceID interface{}
	Search   interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListReposFilteredNameAsc(ctx context.Context, arg ListReposFilteredNameAscParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposFilteredNameAsc,
		arg.SourceID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposFilteredNameDesc = `-- name: ListReposFilteredNameDesc :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE (
    ?1 IS NULL
    OR repos.source_id = ?1
  )
  AND (
    ?2 IS NULL
    OR (
      repos.full_name LIKE '%' || ?2 || '%'
      OR repos.description LIKE '%' || ?2 || '%'
    )
  )
ORDER BY repos.name DESC
LIMIT ?4 OFFSET ?3
`

type ListReposFilteredNameDescParams struct {
	SourceID interface{}
	Search   interface{}
	Offset   int64
	Limit    int64
}

func (q *Queries) ListReposFilteredNameDesc(ctx context.Context, arg ListReposFilteredNameDescParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposFilteredNameDesc,
		arg.SourceID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposForSource = `-- name: ListReposForSource :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE source_id = ?1
ORDER BY ref_id
`

func (q *Queries) ListReposForSource(ctx context.Context, sourceID string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepoAutoExcluded = `-- name: MarkRepoAutoExcluded :exec
UPDATE repos
SET
  status = ?3,
  disabled_at = CASE WHEN disabled_at IS NULL THEN ?4 ELSE disabled_at END,
  updated_at = ?5
WHERE source_id = ?1 AND ref_id = ?2 AND status <> ?3
`

type MarkRepoAutoExcludedParams struct {
	SourceID   string
	RefID      string
	Status     string
	DisabledAt sql.NullString
	UpdatedAt  string
}

func (q *Queries) MarkRepoAutoExcluded(ctx context.Context, arg MarkRepoAutoExcludedParams) error {
	_, err := q.db.ExecContext(ctx, markRepoAutoExcluded,
		arg.SourceID,
		arg.RefID,
		arg.Status,
		arg.DisabledAt,
		arg.UpdatedAt,
	)
	return err
}

const updateRepo = `-- name: UpdateRepo :exec
UPDATE repos
SET
  platform = ?3,
  status = ?4,
  name = ?5,
  full_name = ?6,
  owner = ?7,
  description = ?8,
  html_url = ?9,
  clone_url = ?10,
  ssh_url = ?11,
  default_branch = ?12,
  visibility = ?13,
  is_private = ?14,
  is_fork = ?15,
  is_archived = ?16,
  origin = ?17,
  meta = ?18,
  last_seen_at = ?19,
  disabled_at = ?20,
  updated_at = ?21
WHERE source_id = ?1 AND ref_id = ?2
`

type UpdateRepoParams struct {
	SourceID      string
	RefID         string
	Platform      string
	Status        string
	Name          string
	FullName      string
	Owner         string
	Description   sql.NullString
	HtmlUrl       sql.NullString
	CloneUrl      sql.NullString
	SshUrl        sql.NullString
	DefaultBranch sql.NullString
	Visibility    sql.NullString
	IsPrivate     int64
	IsFork        int64
	IsArchived    int64
	Origin        string
	Meta          string
	LastSeenAt    string
	DisabledAt    sql.NullString
	UpdatedAt     string
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) error {
	_, err := q.db.ExecContext(ctx, updateRepo,
		arg.SourceID,
		arg.RefID,
		arg.Platform,
		arg.Status,
		arg.Name,
		arg.FullName,
		arg.Owner,
		arg.Description,
		arg.HtmlUrl,
		arg.CloneUrl,
		arg.SshUrl,
		arg.DefaultBranch,
		arg.Visibility,
		arg.IsPrivate,
		arg.IsFork,
		arg.IsArchived,
		arg.Origin,
		arg.Meta,
		arg.LastSeenAt,
		arg.DisabledAt,
		arg.UpdatedAt,
	)
	return err
}
