// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRepo = `-- name: CreateRepo :exec
INSERT INTO repos (
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22
)
`

type CreateRepoParams struct {
	SourceID      string
	Platform      string
	RefID         string
	Status        string
	Name          string
	FullName      string
	Owner         string
	Description   sql.NullString
	HtmlUrl       sql.NullString
	CloneUrl      sql.NullString
	SshUrl        sql.NullString
	DefaultBranch sql.NullString
	Visibility    sql.NullString
	IsPrivate     int64
	IsFork        int64
	IsArchived    int64
	Origin        string
	Meta          string
	LastSeenAt    string
	DisabledAt    sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) error {
	_, err := q.db.ExecContext(ctx, createRepo,
		arg.SourceID,
		arg.Platform,
		arg.RefID,
		arg.Status,
		arg.Name,
		arg.FullName,
		arg.Owner,
		arg.Description,
		arg.HtmlUrl,
		arg.CloneUrl,
		arg.SshUrl,
		arg.DefaultBranch,
		arg.Visibility,
		arg.IsPrivate,
		arg.IsFork,
		arg.IsArchived,
		arg.Origin,
		arg.Meta,
		arg.LastSeenAt,
		arg.DisabledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listReposForSource = `-- name: ListReposForSource :many
SELECT
  id,
  source_id,
  platform,
  ref_id,
  status,
  name,
  full_name,
  owner,
  description,
  html_url,
  clone_url,
  ssh_url,
  default_branch,
  visibility,
  is_private,
  is_fork,
  is_archived,
  origin,
  meta,
  last_seen_at,
  disabled_at,
  created_at,
  updated_at
FROM repos
WHERE source_id = ?1
ORDER BY ref_id
`

func (q *Queries) ListReposForSource(ctx context.Context, sourceID string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Platform,
			&i.RefID,
			&i.Status,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.Description,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.SshUrl,
			&i.DefaultBranch,
			&i.Visibility,
			&i.IsPrivate,
			&i.IsFork,
			&i.IsArchived,
			&i.Origin,
			&i.Meta,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepoAutoExcluded = `-- name: MarkRepoAutoExcluded :exec
UPDATE repos
SET
  status = ?3,
  disabled_at = CASE WHEN disabled_at IS NULL THEN ?4 ELSE disabled_at END,
  updated_at = ?5
WHERE source_id = ?1 AND ref_id = ?2 AND status <> ?3
`

type MarkRepoAutoExcludedParams struct {
	SourceID   string
	RefID      string
	Status     string
	DisabledAt sql.NullString
	UpdatedAt  string
}

func (q *Queries) MarkRepoAutoExcluded(ctx context.Context, arg MarkRepoAutoExcludedParams) error {
	_, err := q.db.ExecContext(ctx, markRepoAutoExcluded,
		arg.SourceID,
		arg.RefID,
		arg.Status,
		arg.DisabledAt,
		arg.UpdatedAt,
	)
	return err
}

const updateRepo = `-- name: UpdateRepo :exec
UPDATE repos
SET
  platform = ?3,
  status = ?4,
  name = ?5,
  full_name = ?6,
  owner = ?7,
  description = ?8,
  html_url = ?9,
  clone_url = ?10,
  ssh_url = ?11,
  default_branch = ?12,
  visibility = ?13,
  is_private = ?14,
  is_fork = ?15,
  is_archived = ?16,
  origin = ?17,
  meta = ?18,
  last_seen_at = ?19,
  disabled_at = ?20,
  updated_at = ?21
WHERE source_id = ?1 AND ref_id = ?2
`

type UpdateRepoParams struct {
	SourceID      string
	RefID         string
	Platform      string
	Status        string
	Name          string
	FullName      string
	Owner         string
	Description   sql.NullString
	HtmlUrl       sql.NullString
	CloneUrl      sql.NullString
	SshUrl        sql.NullString
	DefaultBranch sql.NullString
	Visibility    sql.NullString
	IsPrivate     int64
	IsFork        int64
	IsArchived    int64
	Origin        string
	Meta          string
	LastSeenAt    string
	DisabledAt    sql.NullString
	UpdatedAt     string
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) error {
	_, err := q.db.ExecContext(ctx, updateRepo,
		arg.SourceID,
		arg.RefID,
		arg.Platform,
		arg.Status,
		arg.Name,
		arg.FullName,
		arg.Owner,
		arg.Description,
		arg.HtmlUrl,
		arg.CloneUrl,
		arg.SshUrl,
		arg.DefaultBranch,
		arg.Visibility,
		arg.IsPrivate,
		arg.IsFork,
		arg.IsArchived,
		arg.Origin,
		arg.Meta,
		arg.LastSeenAt,
		arg.DisabledAt,
		arg.UpdatedAt,
	)
	return err
}
