// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_runs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTaskRun = `-- name: CreateTaskRun :exec
INSERT INTO task_runs (
  task_id,
  parent_task_id,
  job_id,
  job_type,
  name,
  args_json,
  status,
  created_at,
  started_at,
  finished_at,
  error_message,
  last_progress_summary,
  last_progress_meta_json,
  updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14
)
`

type CreateTaskRunParams struct {
	TaskID               string
	ParentTaskID         sql.NullString
	JobID                string
	JobType              string
	Name                 string
	ArgsJson             sql.NullString
	Status               string
	CreatedAt            string
	StartedAt            string
	FinishedAt           sql.NullString
	ErrorMessage         sql.NullString
	LastProgressSummary  sql.NullString
	LastProgressMetaJson sql.NullString
	UpdatedAt            string
}

func (q *Queries) CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, createTaskRun,
		arg.TaskID,
		arg.ParentTaskID,
		arg.JobID,
		arg.JobType,
		arg.Name,
		arg.ArgsJson,
		arg.Status,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorMessage,
		arg.LastProgressSummary,
		arg.LastProgressMetaJson,
		arg.UpdatedAt,
	)
	return err
}

const createTaskRunLog = `-- name: CreateTaskRunLog :exec
INSERT INTO task_run_logs (
  task_id,
  event_type,
  summary,
  meta_json,
  error_message,
  created_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6
)
`

type CreateTaskRunLogParams struct {
	TaskID       string
	EventType    string
	Summary      sql.NullString
	MetaJson     sql.NullString
	ErrorMessage sql.NullString
	CreatedAt    string
}

func (q *Queries) CreateTaskRunLog(ctx context.Context, arg CreateTaskRunLogParams) error {
	_, err := q.db.ExecContext(ctx, createTaskRunLog,
		arg.TaskID,
		arg.EventType,
		arg.Summary,
		arg.MetaJson,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}

const failTaskRun = `-- name: FailTaskRun :exec
UPDATE task_runs
SET
  status = 'failed',
  finished_at = ?2,
  error_message = ?3,
  updated_at = ?4
WHERE task_id = ?1
`

type FailTaskRunParams struct {
	TaskID       string
	FinishedAt   sql.NullString
	ErrorMessage sql.NullString
	UpdatedAt    string
}

func (q *Queries) FailTaskRun(ctx context.Context, arg FailTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, failTaskRun,
		arg.TaskID,
		arg.FinishedAt,
		arg.ErrorMessage,
		arg.UpdatedAt,
	)
	return err
}

const finishTaskRun = `-- name: FinishTaskRun :exec
UPDATE task_runs
SET
  status = 'finished',
  finished_at = ?2,
  error_message = NULL,
  updated_at = ?3
WHERE task_id = ?1
`

type FinishTaskRunParams struct {
	TaskID     string
	FinishedAt sql.NullString
	UpdatedAt  string
}

func (q *Queries) FinishTaskRun(ctx context.Context, arg FinishTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, finishTaskRun, arg.TaskID, arg.FinishedAt, arg.UpdatedAt)
	return err
}

const getTaskRun = `-- name: GetTaskRun :one
SELECT
  task_id,
  parent_task_id,
  job_id,
  job_type,
  name,
  args_json,
  status,
  created_at,
  started_at,
  finished_at,
  error_message,
  last_progress_summary,
  last_progress_meta_json,
  updated_at
FROM task_runs
WHERE task_id = ?1
LIMIT 1
`

func (q *Queries) GetTaskRun(ctx context.Context, taskID string) (TaskRun, error) {
	row := q.db.QueryRowContext(ctx, getTaskRun, taskID)
	var i TaskRun
	err := row.Scan(
		&i.TaskID,
		&i.ParentTaskID,
		&i.JobID,
		&i.JobType,
		&i.Name,
		&i.ArgsJson,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.LastProgressSummary,
		&i.LastProgressMetaJson,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskRunLogs = `-- name: ListTaskRunLogs :many
SELECT
  id,
  task_id,
  event_type,
  summary,
  meta_json,
  error_message,
  created_at
FROM task_run_logs
WHERE task_id = ?1
ORDER BY created_at, id
`

func (q *Queries) ListTaskRunLogs(ctx context.Context, taskID string) ([]TaskRunLog, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRunLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRunLog
	for rows.Next() {
		var i TaskRunLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.EventType,
			&i.Summary,
			&i.MetaJson,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskRunProgress = `-- name: UpdateTaskRunProgress :exec
UPDATE task_runs
SET
  last_progress_summary = ?2,
  last_progress_meta_json = ?3,
  updated_at = ?4
WHERE task_id = ?1
`

type UpdateTaskRunProgressParams struct {
	TaskID               string
	LastProgressSummary  sql.NullString
	LastProgressMetaJson sql.NullString
	UpdatedAt            string
}

func (q *Queries) UpdateTaskRunProgress(ctx context.Context, arg UpdateTaskRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskRunProgress,
		arg.TaskID,
		arg.LastProgressSummary,
		arg.LastProgressMetaJson,
		arg.UpdatedAt,
	)
	return err
}
