// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitplus/task/v1/task.proto

package taskv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ImSingee/git-plus/pkg/rpc/gitplus/task/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "gitplus.task.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceGetTaskRuntimeProcedure is the fully-qualified name of the TaskService's
	// GetTaskRuntime RPC.
	TaskServiceGetTaskRuntimeProcedure = "/gitplus.task.v1.TaskService/GetTaskRuntime"
	// TaskServiceListTaskRunsProcedure is the fully-qualified name of the TaskService's ListTaskRuns
	// RPC.
	TaskServiceListTaskRunsProcedure = "/gitplus.task.v1.TaskService/ListTaskRuns"
	// TaskServiceGetTaskRunProcedure is the fully-qualified name of the TaskService's GetTaskRun RPC.
	TaskServiceGetTaskRunProcedure = "/gitplus.task.v1.TaskService/GetTaskRun"
	// TaskServiceListTaskRunLogsProcedure is the fully-qualified name of the TaskService's
	// ListTaskRunLogs RPC.
	TaskServiceListTaskRunLogsProcedure = "/gitplus.task.v1.TaskService/ListTaskRunLogs"
	// TaskServiceEnqueueFullSyncProcedure is the fully-qualified name of the TaskService's
	// EnqueueFullSync RPC.
	TaskServiceEnqueueFullSyncProcedure = "/gitplus.task.v1.TaskService/EnqueueFullSync"
	// TaskServiceEnqueueSourceSyncProcedure is the fully-qualified name of the TaskService's
	// EnqueueSourceSync RPC.
	TaskServiceEnqueueSourceSyncProcedure = "/gitplus.task.v1.TaskService/EnqueueSourceSync"
	// TaskServiceCancelQueuedTaskProcedure is the fully-qualified name of the TaskService's
	// CancelQueuedTask RPC.
	TaskServiceCancelQueuedTaskProcedure = "/gitplus.task.v1.TaskService/CancelQueuedTask"
)

// TaskServiceClient is a client for the gitplus.task.v1.TaskService service.
type TaskServiceClient interface {
	GetTaskRuntime(context.Context, *connect.Request[v1.GetTaskRuntimeRequest]) (*connect.Response[v1.GetTaskRuntimeResponse], error)
	ListTaskRuns(context.Context, *connect.Request[v1.ListTaskRunsRequest]) (*connect.Response[v1.ListTaskRunsResponse], error)
	GetTaskRun(context.Context, *connect.Request[v1.GetTaskRunRequest]) (*connect.Response[v1.GetTaskRunResponse], error)
	ListTaskRunLogs(context.Context, *connect.Request[v1.ListTaskRunLogsRequest]) (*connect.Response[v1.ListTaskRunLogsResponse], error)
	EnqueueFullSync(context.Context, *connect.Request[v1.EnqueueFullSyncRequest]) (*connect.Response[v1.EnqueueFullSyncResponse], error)
	EnqueueSourceSync(context.Context, *connect.Request[v1.EnqueueSourceSyncRequest]) (*connect.Response[v1.EnqueueSourceSyncResponse], error)
	CancelQueuedTask(context.Context, *connect.Request[v1.CancelQueuedTaskRequest]) (*connect.Response[v1.CancelQueuedTaskResponse], error)
}

// NewTaskServiceClient constructs a client for the gitplus.task.v1.TaskService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_gitplus_task_v1_task_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		getTaskRuntime: connect.NewClient[v1.GetTaskRuntimeRequest, v1.GetTaskRuntimeResponse](
			httpClient,
			baseURL+TaskServiceGetTaskRuntimeProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTaskRuntime")),
			connect.WithClientOptions(opts...),
		),
		listTaskRuns: connect.NewClient[v1.ListTaskRunsRequest, v1.ListTaskRunsResponse](
			httpClient,
			baseURL+TaskServiceListTaskRunsProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListTaskRuns")),
			connect.WithClientOptions(opts...),
		),
		getTaskRun: connect.NewClient[v1.GetTaskRunRequest, v1.GetTaskRunResponse](
			httpClient,
			baseURL+TaskServiceGetTaskRunProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTaskRun")),
			connect.WithClientOptions(opts...),
		),
		listTaskRunLogs: connect.NewClient[v1.ListTaskRunLogsRequest, v1.ListTaskRunLogsResponse](
			httpClient,
			baseURL+TaskServiceListTaskRunLogsProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListTaskRunLogs")),
			connect.WithClientOptions(opts...),
		),
		enqueueFullSync: connect.NewClient[v1.EnqueueFullSyncRequest, v1.EnqueueFullSyncResponse](
			httpClient,
			baseURL+TaskServiceEnqueueFullSyncProcedure,
			connect.WithSchema(taskServiceMethods.ByName("EnqueueFullSync")),
			connect.WithClientOptions(opts...),
		),
		enqueueSourceSync: connect.NewClient[v1.EnqueueSourceSyncRequest, v1.EnqueueSourceSyncResponse](
			httpClient,
			baseURL+TaskServiceEnqueueSourceSyncProcedure,
			connect.WithSchema(taskServiceMethods.ByName("EnqueueSourceSync")),
			connect.WithClientOptions(opts...),
		),
		cancelQueuedTask: connect.NewClient[v1.CancelQueuedTaskRequest, v1.CancelQueuedTaskResponse](
			httpClient,
			baseURL+TaskServiceCancelQueuedTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CancelQueuedTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	getTaskRuntime    *connect.Client[v1.GetTaskRuntimeRequest, v1.GetTaskRuntimeResponse]
	listTaskRuns      *connect.Client[v1.ListTaskRunsRequest, v1.ListTaskRunsResponse]
	getTaskRun        *connect.Client[v1.GetTaskRunRequest, v1.GetTaskRunResponse]
	listTaskRunLogs   *connect.Client[v1.ListTaskRunLogsRequest, v1.ListTaskRunLogsResponse]
	enqueueFullSync   *connect.Client[v1.EnqueueFullSyncRequest, v1.EnqueueFullSyncResponse]
	enqueueSourceSync *connect.Client[v1.EnqueueSourceSyncRequest, v1.EnqueueSourceSyncResponse]
	cancelQueuedTask  *connect.Client[v1.CancelQueuedTaskRequest, v1.CancelQueuedTaskResponse]
}

// GetTaskRuntime calls gitplus.task.v1.TaskService.GetTaskRuntime.
func (c *taskServiceClient) GetTaskRuntime(ctx context.Context, req *connect.Request[v1.GetTaskRuntimeRequest]) (*connect.Response[v1.GetTaskRuntimeResponse], error) {
	return c.getTaskRuntime.CallUnary(ctx, req)
}

// ListTaskRuns calls gitplus.task.v1.TaskService.ListTaskRuns.
func (c *taskServiceClient) ListTaskRuns(ctx context.Context, req *connect.Request[v1.ListTaskRunsRequest]) (*connect.Response[v1.ListTaskRunsResponse], error) {
	return c.listTaskRuns.CallUnary(ctx, req)
}

// GetTaskRun calls gitplus.task.v1.TaskService.GetTaskRun.
func (c *taskServiceClient) GetTaskRun(ctx context.Context, req *connect.Request[v1.GetTaskRunRequest]) (*connect.Response[v1.GetTaskRunResponse], error) {
	return c.getTaskRun.CallUnary(ctx, req)
}

// ListTaskRunLogs calls gitplus.task.v1.TaskService.ListTaskRunLogs.
func (c *taskServiceClient) ListTaskRunLogs(ctx context.Context, req *connect.Request[v1.ListTaskRunLogsRequest]) (*connect.Response[v1.ListTaskRunLogsResponse], error) {
	return c.listTaskRunLogs.CallUnary(ctx, req)
}

// EnqueueFullSync calls gitplus.task.v1.TaskService.EnqueueFullSync.
func (c *taskServiceClient) EnqueueFullSync(ctx context.Context, req *connect.Request[v1.EnqueueFullSyncRequest]) (*connect.Response[v1.EnqueueFullSyncResponse], error) {
	return c.enqueueFullSync.CallUnary(ctx, req)
}

// EnqueueSourceSync calls gitplus.task.v1.TaskService.EnqueueSourceSync.
func (c *taskServiceClient) EnqueueSourceSync(ctx context.Context, req *connect.Request[v1.EnqueueSourceSyncRequest]) (*connect.Response[v1.EnqueueSourceSyncResponse], error) {
	return c.enqueueSourceSync.CallUnary(ctx, req)
}

// CancelQueuedTask calls gitplus.task.v1.TaskService.CancelQueuedTask.
func (c *taskServiceClient) CancelQueuedTask(ctx context.Context, req *connect.Request[v1.CancelQueuedTaskRequest]) (*connect.Response[v1.CancelQueuedTaskResponse], error) {
	return c.cancelQueuedTask.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the gitplus.task.v1.TaskService service.
type TaskServiceHandler interface {
	GetTaskRuntime(context.Context, *connect.Request[v1.GetTaskRuntimeRequest]) (*connect.Response[v1.GetTaskRuntimeResponse], error)
	ListTaskRuns(context.Context, *connect.Request[v1.ListTaskRunsRequest]) (*connect.Response[v1.ListTaskRunsResponse], error)
	GetTaskRun(context.Context, *connect.Request[v1.GetTaskRunRequest]) (*connect.Response[v1.GetTaskRunResponse], error)
	ListTaskRunLogs(context.Context, *connect.Request[v1.ListTaskRunLogsRequest]) (*connect.Response[v1.ListTaskRunLogsResponse], error)
	EnqueueFullSync(context.Context, *connect.Request[v1.EnqueueFullSyncRequest]) (*connect.Response[v1.EnqueueFullSyncResponse], error)
	EnqueueSourceSync(context.Context, *connect.Request[v1.EnqueueSourceSyncRequest]) (*connect.Response[v1.EnqueueSourceSyncResponse], error)
	CancelQueuedTask(context.Context, *connect.Request[v1.CancelQueuedTaskRequest]) (*connect.Response[v1.CancelQueuedTaskResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_gitplus_task_v1_task_proto.Services().ByName("TaskService").Methods()
	taskServiceGetTaskRuntimeHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskRuntimeProcedure,
		svc.GetTaskRuntime,
		connect.WithSchema(taskServiceMethods.ByName("GetTaskRuntime")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListTaskRunsHandler := connect.NewUnaryHandler(
		TaskServiceListTaskRunsProcedure,
		svc.ListTaskRuns,
		connect.WithSchema(taskServiceMethods.ByName("ListTaskRuns")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskRunHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskRunProcedure,
		svc.GetTaskRun,
		connect.WithSchema(taskServiceMethods.ByName("GetTaskRun")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListTaskRunLogsHandler := connect.NewUnaryHandler(
		TaskServiceListTaskRunLogsProcedure,
		svc.ListTaskRunLogs,
		connect.WithSchema(taskServiceMethods.ByName("ListTaskRunLogs")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceEnqueueFullSyncHandler := connect.NewUnaryHandler(
		TaskServiceEnqueueFullSyncProcedure,
		svc.EnqueueFullSync,
		connect.WithSchema(taskServiceMethods.ByName("EnqueueFullSync")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceEnqueueSourceSyncHandler := connect.NewUnaryHandler(
		TaskServiceEnqueueSourceSyncProcedure,
		svc.EnqueueSourceSync,
		connect.WithSchema(taskServiceMethods.ByName("EnqueueSourceSync")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCancelQueuedTaskHandler := connect.NewUnaryHandler(
		TaskServiceCancelQueuedTaskProcedure,
		svc.CancelQueuedTask,
		connect.WithSchema(taskServiceMethods.ByName("CancelQueuedTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitplus.task.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceGetTaskRuntimeProcedure:
			taskServiceGetTaskRuntimeHandler.ServeHTTP(w, r)
		case TaskServiceListTaskRunsProcedure:
			taskServiceListTaskRunsHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskRunProcedure:
			taskServiceGetTaskRunHandler.ServeHTTP(w, r)
		case TaskServiceListTaskRunLogsProcedure:
			taskServiceListTaskRunLogsHandler.ServeHTTP(w, r)
		case TaskServiceEnqueueFullSyncProcedure:
			taskServiceEnqueueFullSyncHandler.ServeHTTP(w, r)
		case TaskServiceEnqueueSourceSyncProcedure:
			taskServiceEnqueueSourceSyncHandler.ServeHTTP(w, r)
		case TaskServiceCancelQueuedTaskProcedure:
			taskServiceCancelQueuedTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) GetTaskRuntime(context.Context, *connect.Request[v1.GetTaskRuntimeRequest]) (*connect.Response[v1.GetTaskRuntimeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.GetTaskRuntime is not implemented"))
}

func (UnimplementedTaskServiceHandler) ListTaskRuns(context.Context, *connect.Request[v1.ListTaskRunsRequest]) (*connect.Response[v1.ListTaskRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.ListTaskRuns is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTaskRun(context.Context, *connect.Request[v1.GetTaskRunRequest]) (*connect.Response[v1.GetTaskRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.GetTaskRun is not implemented"))
}

func (UnimplementedTaskServiceHandler) ListTaskRunLogs(context.Context, *connect.Request[v1.ListTaskRunLogsRequest]) (*connect.Response[v1.ListTaskRunLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.ListTaskRunLogs is not implemented"))
}

func (UnimplementedTaskServiceHandler) EnqueueFullSync(context.Context, *connect.Request[v1.EnqueueFullSyncRequest]) (*connect.Response[v1.EnqueueFullSyncResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.EnqueueFullSync is not implemented"))
}

func (UnimplementedTaskServiceHandler) EnqueueSourceSync(context.Context, *connect.Request[v1.EnqueueSourceSyncRequest]) (*connect.Response[v1.EnqueueSourceSyncResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.EnqueueSourceSync is not implemented"))
}

func (UnimplementedTaskServiceHandler) CancelQueuedTask(context.Context, *connect.Request[v1.CancelQueuedTaskRequest]) (*connect.Response[v1.CancelQueuedTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.task.v1.TaskService.CancelQueuedTask is not implemented"))
}
