// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitplus/cron/v1/cron.proto

package cronv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CronRuntime struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Enabled       *bool                    `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	Cron          *string                  `protobuf:"bytes,2,opt,name=cron" json:"cron,omitempty"`
	NextRuns      []*timestamppb.Timestamp `protobuf:"bytes,4,rep,name=next_runs,json=nextRuns" json:"next_runs,omitempty"`
	LastError     *string                  `protobuf:"bytes,5,opt,name=last_error,json=lastError" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRuntime) Reset() {
	*x = CronRuntime{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRuntime) ProtoMessage() {}

func (x *CronRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRuntime.ProtoReflect.Descriptor instead.
func (*CronRuntime) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CronRuntime) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *CronRuntime) GetCron() string {
	if x != nil && x.Cron != nil {
		return *x.Cron
	}
	return ""
}

func (x *CronRuntime) GetNextRuns() []*timestamppb.Timestamp {
	if x != nil {
		return x.NextRuns
	}
	return nil
}

func (x *CronRuntime) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

type GetCronRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronRuntimeRequest) Reset() {
	*x = GetCronRuntimeRequest{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronRuntimeRequest) ProtoMessage() {}

func (x *GetCronRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronRuntimeRequest.ProtoReflect.Descriptor instead.
func (*GetCronRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

type GetCronRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *CronRuntime           `protobuf:"bytes,1,opt,name=runtime" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronRuntimeResponse) Reset() {
	*x = GetCronRuntimeResponse{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronRuntimeResponse) ProtoMessage() {}

func (x *GetCronRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronRuntimeResponse.ProtoReflect.Descriptor instead.
func (*GetCronRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *GetCronRuntimeResponse) GetRuntime() *CronRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type UpdateCronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cron          *string                `protobuf:"bytes,1,opt,name=cron" json:"cron,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronRequest) Reset() {
	*x = UpdateCronRequest{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronRequest) ProtoMessage() {}

func (x *UpdateCronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronRequest.ProtoReflect.Descriptor instead.
func (*UpdateCronRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCronRequest) GetCron() string {
	if x != nil && x.Cron != nil {
		return *x.Cron
	}
	return ""
}

type UpdateCronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *CronRuntime           `protobuf:"bytes,1,opt,name=runtime" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronResponse) Reset() {
	*x = UpdateCronResponse{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronResponse) ProtoMessage() {}

func (x *UpdateCronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronResponse.ProtoReflect.Descriptor instead.
func (*UpdateCronResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCronResponse) GetRuntime() *CronRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type ReloadCronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadCronRequest) Reset() {
	*x = ReloadCronRequest{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadCronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCronRequest) ProtoMessage() {}

func (x *ReloadCronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCronRequest.ProtoReflect.Descriptor instead.
func (*ReloadCronRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{5}
}

type ReloadCronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *CronRuntime           `protobuf:"bytes,1,opt,name=runtime" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadCronResponse) Reset() {
	*x = ReloadCronResponse{}
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadCronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCronResponse) ProtoMessage() {}

func (x *ReloadCronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_cron_v1_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCronResponse.ProtoReflect.Descriptor instead.
func (*ReloadCronResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_cron_v1_cron_proto_rawDescGZIP(), []int{6}
}

func (x *ReloadCronResponse) GetRuntime() *CronRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

var File_gitplus_cron_v1_cron_proto protoreflect.FileDescriptor

const file_gitplus_cron_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x1agitplus/cron/v1/cron.proto\x12\x0fgitplus.cron.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n" +
	"\vCronRuntime\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04cron\x18\x02 \x01(\tR\x04cron\x127\n" +
	"\tnext_runs\x18\x04 \x03(\v2\x1a.google.protobuf.TimestampR\bnextRuns\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastErrorJ\x04\b\x03\x10\x04\"\x17\n" +
	"\x15GetCronRuntimeRequest\"P\n" +
	"\x16GetCronRuntimeResponse\x126\n" +
	"\aruntime\x18\x01 \x01(\v2\x1c.gitplus.cron.v1.CronRuntimeR\aruntime\"'\n" +
	"\x11UpdateCronRequest\x12\x12\n" +
	"\x04cron\x18\x01 \x01(\tR\x04cron\"L\n" +
	"\x12UpdateCronResponse\x126\n" +
	"\aruntime\x18\x01 \x01(\v2\x1c.gitplus.cron.v1.CronRuntimeR\aruntime\"\x13\n" +
	"\x11ReloadCronRequest\"L\n" +
	"\x12ReloadCronResponse\x126\n" +
	"\aruntime\x18\x01 \x01(\v2\x1c.gitplus.cron.v1.CronRuntimeR\aruntime2\x9e\x02\n" +
	"\vCronService\x12a\n" +
	"\x0eGetCronRuntime\x12&.gitplus.cron.v1.GetCronRuntimeRequest\x1a'.gitplus.cron.v1.GetCronRuntimeResponse\x12U\n" +
	"\n" +
	"UpdateCron\x12\".gitplus.cron.v1.UpdateCronRequest\x1a#.gitplus.cron.v1.UpdateCronResponse\x12U\n" +
	"\n" +
	"ReloadCron\x12\".gitplus.cron.v1.ReloadCronRequest\x1a#.gitplus.cron.v1.ReloadCronResponseB\xc5\x01\n" +
	"\x13com.gitplus.cron.v1B\tCronProtoP\x01Z;github.com/ImSingee/git-plus/pkg/rpc/gitplus/cron/v1;cronv1\xa2\x02\x03GCX\xaa\x02\x0fGitplus.Cron.V1\xca\x02\x0fGitplus\\Cron\\V1\xe2\x02\x1bGitplus\\Cron\\V1\\GPBMetadata\xea\x02\x11Gitplus::Cron::V1\x92\x03\a\xd2>\x02\x10\x01\b\x01b\beditionsp\xe8\a"

var (
	file_gitplus_cron_v1_cron_proto_rawDescOnce sync.Once
	file_gitplus_cron_v1_cron_proto_rawDescData []byte
)

func file_gitplus_cron_v1_cron_proto_rawDescGZIP() []byte {
	file_gitplus_cron_v1_cron_proto_rawDescOnce.Do(func() {
		file_gitplus_cron_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitplus_cron_v1_cron_proto_rawDesc), len(file_gitplus_cron_v1_cron_proto_rawDesc)))
	})
	return file_gitplus_cron_v1_cron_proto_rawDescData
}

var file_gitplus_cron_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gitplus_cron_v1_cron_proto_goTypes = []any{
	(*CronRuntime)(nil),            // 0: gitplus.cron.v1.CronRuntime
	(*GetCronRuntimeRequest)(nil),  // 1: gitplus.cron.v1.GetCronRuntimeRequest
	(*GetCronRuntimeResponse)(nil), // 2: gitplus.cron.v1.GetCronRuntimeResponse
	(*UpdateCronRequest)(nil),      // 3: gitplus.cron.v1.UpdateCronRequest
	(*UpdateCronResponse)(nil),     // 4: gitplus.cron.v1.UpdateCronResponse
	(*ReloadCronRequest)(nil),      // 5: gitplus.cron.v1.ReloadCronRequest
	(*ReloadCronResponse)(nil),     // 6: gitplus.cron.v1.ReloadCronResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_gitplus_cron_v1_cron_proto_depIdxs = []int32{
	7, // 0: gitplus.cron.v1.CronRuntime.next_runs:type_name -> google.protobuf.Timestamp
	0, // 1: gitplus.cron.v1.GetCronRuntimeResponse.runtime:type_name -> gitplus.cron.v1.CronRuntime
	0, // 2: gitplus.cron.v1.UpdateCronResponse.runtime:type_name -> gitplus.cron.v1.CronRuntime
	0, // 3: gitplus.cron.v1.ReloadCronResponse.runtime:type_name -> gitplus.cron.v1.CronRuntime
	1, // 4: gitplus.cron.v1.CronService.GetCronRuntime:input_type -> gitplus.cron.v1.GetCronRuntimeRequest
	3, // 5: gitplus.cron.v1.CronService.UpdateCron:input_type -> gitplus.cron.v1.UpdateCronRequest
	5, // 6: gitplus.cron.v1.CronService.ReloadCron:input_type -> gitplus.cron.v1.ReloadCronRequest
	2, // 7: gitplus.cron.v1.CronService.GetCronRuntime:output_type -> gitplus.cron.v1.GetCronRuntimeResponse
	4, // 8: gitplus.cron.v1.CronService.UpdateCron:output_type -> gitplus.cron.v1.UpdateCronResponse
	6, // 9: gitplus.cron.v1.CronService.ReloadCron:output_type -> gitplus.cron.v1.ReloadCronResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gitplus_cron_v1_cron_proto_init() }
func file_gitplus_cron_v1_cron_proto_init() {
	if File_gitplus_cron_v1_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitplus_cron_v1_cron_proto_rawDesc), len(file_gitplus_cron_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitplus_cron_v1_cron_proto_goTypes,
		DependencyIndexes: file_gitplus_cron_v1_cron_proto_depIdxs,
		MessageInfos:      file_gitplus_cron_v1_cron_proto_msgTypes,
	}.Build()
	File_gitplus_cron_v1_cron_proto = out.File
	file_gitplus_cron_v1_cron_proto_goTypes = nil
	file_gitplus_cron_v1_cron_proto_depIdxs = nil
}
