// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gitplus/cron/v1/cron.proto

package cronv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ImSingee/git-plus/pkg/rpc/gitplus/cron/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CronServiceName is the fully-qualified name of the CronService service.
	CronServiceName = "gitplus.cron.v1.CronService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CronServiceGetCronRuntimeProcedure is the fully-qualified name of the CronService's
	// GetCronRuntime RPC.
	CronServiceGetCronRuntimeProcedure = "/gitplus.cron.v1.CronService/GetCronRuntime"
	// CronServiceUpdateCronProcedure is the fully-qualified name of the CronService's UpdateCron RPC.
	CronServiceUpdateCronProcedure = "/gitplus.cron.v1.CronService/UpdateCron"
	// CronServiceReloadCronProcedure is the fully-qualified name of the CronService's ReloadCron RPC.
	CronServiceReloadCronProcedure = "/gitplus.cron.v1.CronService/ReloadCron"
)

// CronServiceClient is a client for the gitplus.cron.v1.CronService service.
type CronServiceClient interface {
	GetCronRuntime(context.Context, *connect.Request[v1.GetCronRuntimeRequest]) (*connect.Response[v1.GetCronRuntimeResponse], error)
	UpdateCron(context.Context, *connect.Request[v1.UpdateCronRequest]) (*connect.Response[v1.UpdateCronResponse], error)
	ReloadCron(context.Context, *connect.Request[v1.ReloadCronRequest]) (*connect.Response[v1.ReloadCronResponse], error)
}

// NewCronServiceClient constructs a client for the gitplus.cron.v1.CronService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCronServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CronServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cronServiceMethods := v1.File_gitplus_cron_v1_cron_proto.Services().ByName("CronService").Methods()
	return &cronServiceClient{
		getCronRuntime: connect.NewClient[v1.GetCronRuntimeRequest, v1.GetCronRuntimeResponse](
			httpClient,
			baseURL+CronServiceGetCronRuntimeProcedure,
			connect.WithSchema(cronServiceMethods.ByName("GetCronRuntime")),
			connect.WithClientOptions(opts...),
		),
		updateCron: connect.NewClient[v1.UpdateCronRequest, v1.UpdateCronResponse](
			httpClient,
			baseURL+CronServiceUpdateCronProcedure,
			connect.WithSchema(cronServiceMethods.ByName("UpdateCron")),
			connect.WithClientOptions(opts...),
		),
		reloadCron: connect.NewClient[v1.ReloadCronRequest, v1.ReloadCronResponse](
			httpClient,
			baseURL+CronServiceReloadCronProcedure,
			connect.WithSchema(cronServiceMethods.ByName("ReloadCron")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cronServiceClient implements CronServiceClient.
type cronServiceClient struct {
	getCronRuntime *connect.Client[v1.GetCronRuntimeRequest, v1.GetCronRuntimeResponse]
	updateCron     *connect.Client[v1.UpdateCronRequest, v1.UpdateCronResponse]
	reloadCron     *connect.Client[v1.ReloadCronRequest, v1.ReloadCronResponse]
}

// GetCronRuntime calls gitplus.cron.v1.CronService.GetCronRuntime.
func (c *cronServiceClient) GetCronRuntime(ctx context.Context, req *connect.Request[v1.GetCronRuntimeRequest]) (*connect.Response[v1.GetCronRuntimeResponse], error) {
	return c.getCronRuntime.CallUnary(ctx, req)
}

// UpdateCron calls gitplus.cron.v1.CronService.UpdateCron.
func (c *cronServiceClient) UpdateCron(ctx context.Context, req *connect.Request[v1.UpdateCronRequest]) (*connect.Response[v1.UpdateCronResponse], error) {
	return c.updateCron.CallUnary(ctx, req)
}

// ReloadCron calls gitplus.cron.v1.CronService.ReloadCron.
func (c *cronServiceClient) ReloadCron(ctx context.Context, req *connect.Request[v1.ReloadCronRequest]) (*connect.Response[v1.ReloadCronResponse], error) {
	return c.reloadCron.CallUnary(ctx, req)
}

// CronServiceHandler is an implementation of the gitplus.cron.v1.CronService service.
type CronServiceHandler interface {
	GetCronRuntime(context.Context, *connect.Request[v1.GetCronRuntimeRequest]) (*connect.Response[v1.GetCronRuntimeResponse], error)
	UpdateCron(context.Context, *connect.Request[v1.UpdateCronRequest]) (*connect.Response[v1.UpdateCronResponse], error)
	ReloadCron(context.Context, *connect.Request[v1.ReloadCronRequest]) (*connect.Response[v1.ReloadCronResponse], error)
}

// NewCronServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCronServiceHandler(svc CronServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cronServiceMethods := v1.File_gitplus_cron_v1_cron_proto.Services().ByName("CronService").Methods()
	cronServiceGetCronRuntimeHandler := connect.NewUnaryHandler(
		CronServiceGetCronRuntimeProcedure,
		svc.GetCronRuntime,
		connect.WithSchema(cronServiceMethods.ByName("GetCronRuntime")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceUpdateCronHandler := connect.NewUnaryHandler(
		CronServiceUpdateCronProcedure,
		svc.UpdateCron,
		connect.WithSchema(cronServiceMethods.ByName("UpdateCron")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceReloadCronHandler := connect.NewUnaryHandler(
		CronServiceReloadCronProcedure,
		svc.ReloadCron,
		connect.WithSchema(cronServiceMethods.ByName("ReloadCron")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitplus.cron.v1.CronService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CronServiceGetCronRuntimeProcedure:
			cronServiceGetCronRuntimeHandler.ServeHTTP(w, r)
		case CronServiceUpdateCronProcedure:
			cronServiceUpdateCronHandler.ServeHTTP(w, r)
		case CronServiceReloadCronProcedure:
			cronServiceReloadCronHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCronServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCronServiceHandler struct{}

func (UnimplementedCronServiceHandler) GetCronRuntime(context.Context, *connect.Request[v1.GetCronRuntimeRequest]) (*connect.Response[v1.GetCronRuntimeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.cron.v1.CronService.GetCronRuntime is not implemented"))
}

func (UnimplementedCronServiceHandler) UpdateCron(context.Context, *connect.Request[v1.UpdateCronRequest]) (*connect.Response[v1.UpdateCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.cron.v1.CronService.UpdateCron is not implemented"))
}

func (UnimplementedCronServiceHandler) ReloadCron(context.Context, *connect.Request[v1.ReloadCronRequest]) (*connect.Response[v1.ReloadCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitplus.cron.v1.CronService.ReloadCron is not implemented"))
}
