// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitplus/task/v1/task.proto

package taskv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_QUEUED      TaskState = 1
	TaskState_TASK_STATE_RUNNING     TaskState = 2
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_QUEUED",
		2: "TASK_STATE_RUNNING",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_QUEUED":      1,
		"TASK_STATE_RUNNING":     2,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_gitplus_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_gitplus_task_v1_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{0}
}

type TaskEnqueueResult int32

const (
	TaskEnqueueResult_TASK_ENQUEUE_RESULT_UNSPECIFIED TaskEnqueueResult = 0
	TaskEnqueueResult_TASK_ENQUEUE_RESULT_STARTED     TaskEnqueueResult = 1
	TaskEnqueueResult_TASK_ENQUEUE_RESULT_QUEUED      TaskEnqueueResult = 2
	TaskEnqueueResult_TASK_ENQUEUE_RESULT_DEDUPED     TaskEnqueueResult = 3
)

// Enum value maps for TaskEnqueueResult.
var (
	TaskEnqueueResult_name = map[int32]string{
		0: "TASK_ENQUEUE_RESULT_UNSPECIFIED",
		1: "TASK_ENQUEUE_RESULT_STARTED",
		2: "TASK_ENQUEUE_RESULT_QUEUED",
		3: "TASK_ENQUEUE_RESULT_DEDUPED",
	}
	TaskEnqueueResult_value = map[string]int32{
		"TASK_ENQUEUE_RESULT_UNSPECIFIED": 0,
		"TASK_ENQUEUE_RESULT_STARTED":     1,
		"TASK_ENQUEUE_RESULT_QUEUED":      2,
		"TASK_ENQUEUE_RESULT_DEDUPED":     3,
	}
)

func (x TaskEnqueueResult) Enum() *TaskEnqueueResult {
	p := new(TaskEnqueueResult)
	*p = x
	return p
}

func (x TaskEnqueueResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEnqueueResult) Descriptor() protoreflect.EnumDescriptor {
	return file_gitplus_task_v1_task_proto_enumTypes[1].Descriptor()
}

func (TaskEnqueueResult) Type() protoreflect.EnumType {
	return &file_gitplus_task_v1_task_proto_enumTypes[1]
}

func (x TaskEnqueueResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEnqueueResult.Descriptor instead.
func (TaskEnqueueResult) EnumDescriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{1}
}

type TaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *string                `protobuf:"bytes,1,opt,name=summary" json:"summary,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskProgress) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *TaskProgress) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TaskProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	JobId         *string                `protobuf:"bytes,2,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	JobType       *string                `protobuf:"bytes,3,opt,name=job_type,json=jobType" json:"job_type,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	State         *TaskState             `protobuf:"varint,5,opt,name=state,enum=gitplus.task.v1.TaskState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	Progress      *TaskProgress          `protobuf:"bytes,8,opt,name=progress" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *Task) GetJobType() string {
	if x != nil && x.JobType != nil {
		return *x.JobType
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetProgress() *TaskProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetTaskRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRuntimeRequest) Reset() {
	*x = GetTaskRuntimeRequest{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRuntimeRequest) ProtoMessage() {}

func (x *GetTaskRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRuntimeRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{2}
}

type GetTaskRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunningTask   *Task                  `protobuf:"bytes,1,opt,name=running_task,json=runningTask" json:"running_task,omitempty"`
	QueuedTasks   []*Task                `protobuf:"bytes,2,rep,name=queued_tasks,json=queuedTasks" json:"queued_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRuntimeResponse) Reset() {
	*x = GetTaskRuntimeResponse{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRuntimeResponse) ProtoMessage() {}

func (x *GetTaskRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRuntimeResponse.ProtoReflect.Descriptor instead.
func (*GetTaskRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRuntimeResponse) GetRunningTask() *Task {
	if x != nil {
		return x.RunningTask
	}
	return nil
}

func (x *GetTaskRuntimeResponse) GetQueuedTasks() []*Task {
	if x != nil {
		return x.QueuedTasks
	}
	return nil
}

type EnqueueFullSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueFullSyncRequest) Reset() {
	*x = EnqueueFullSyncRequest{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueFullSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueFullSyncRequest) ProtoMessage() {}

func (x *EnqueueFullSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueFullSyncRequest.ProtoReflect.Descriptor instead.
func (*EnqueueFullSyncRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{4}
}

type EnqueueFullSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TaskEnqueueResult     `protobuf:"varint,1,opt,name=result,enum=gitplus.task.v1.TaskEnqueueResult" json:"result,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueFullSyncResponse) Reset() {
	*x = EnqueueFullSyncResponse{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueFullSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueFullSyncResponse) ProtoMessage() {}

func (x *EnqueueFullSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueFullSyncResponse.ProtoReflect.Descriptor instead.
func (*EnqueueFullSyncResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *EnqueueFullSyncResponse) GetResult() TaskEnqueueResult {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return TaskEnqueueResult_TASK_ENQUEUE_RESULT_UNSPECIFIED
}

func (x *EnqueueFullSyncResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type EnqueueSourceSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *string                `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueSourceSyncRequest) Reset() {
	*x = EnqueueSourceSyncRequest{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueSourceSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueSourceSyncRequest) ProtoMessage() {}

func (x *EnqueueSourceSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueSourceSyncRequest.ProtoReflect.Descriptor instead.
func (*EnqueueSourceSyncRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *EnqueueSourceSyncRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

type EnqueueSourceSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TaskEnqueueResult     `protobuf:"varint,1,opt,name=result,enum=gitplus.task.v1.TaskEnqueueResult" json:"result,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueSourceSyncResponse) Reset() {
	*x = EnqueueSourceSyncResponse{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueSourceSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueSourceSyncResponse) ProtoMessage() {}

func (x *EnqueueSourceSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueSourceSyncResponse.ProtoReflect.Descriptor instead.
func (*EnqueueSourceSyncResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *EnqueueSourceSyncResponse) GetResult() TaskEnqueueResult {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return TaskEnqueueResult_TASK_ENQUEUE_RESULT_UNSPECIFIED
}

func (x *EnqueueSourceSyncResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CancelQueuedTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueuedTaskRequest) Reset() {
	*x = CancelQueuedTaskRequest{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueuedTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueuedTaskRequest) ProtoMessage() {}

func (x *CancelQueuedTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueuedTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelQueuedTaskRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *CancelQueuedTaskRequest) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

type CancelQueuedTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueuedTaskResponse) Reset() {
	*x = CancelQueuedTaskResponse{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueuedTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueuedTaskResponse) ProtoMessage() {}

func (x *CancelQueuedTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueuedTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelQueuedTaskResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{9}
}

func (x *CancelQueuedTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type EnqueueTestTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variant       *int32                 `protobuf:"varint,1,opt,name=variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTestTaskRequest) Reset() {
	*x = EnqueueTestTaskRequest{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTestTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTestTaskRequest) ProtoMessage() {}

func (x *EnqueueTestTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTestTaskRequest.ProtoReflect.Descriptor instead.
func (*EnqueueTestTaskRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{10}
}

func (x *EnqueueTestTaskRequest) GetVariant() int32 {
	if x != nil && x.Variant != nil {
		return *x.Variant
	}
	return 0
}

type EnqueueTestTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TaskEnqueueResult     `protobuf:"varint,1,opt,name=result,enum=gitplus.task.v1.TaskEnqueueResult" json:"result,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTestTaskResponse) Reset() {
	*x = EnqueueTestTaskResponse{}
	mi := &file_gitplus_task_v1_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTestTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTestTaskResponse) ProtoMessage() {}

func (x *EnqueueTestTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_task_v1_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTestTaskResponse.ProtoReflect.Descriptor instead.
func (*EnqueueTestTaskResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_task_v1_task_proto_rawDescGZIP(), []int{11}
}

func (x *EnqueueTestTaskResponse) GetResult() TaskEnqueueResult {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return TaskEnqueueResult_TASK_ENQUEUE_RESULT_UNSPECIFIED
}

func (x *EnqueueTestTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_gitplus_task_v1_task_proto protoreflect.FileDescriptor

const file_gitplus_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x1agitplus/task/v1/task.proto\x12\x0fgitplus.task.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\fTaskProgress\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04meta\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc8\x02\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x120\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1a.gitplus.task.v1.TaskStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\bprogress\x18\b \x01(\v2\x1d.gitplus.task.v1.TaskProgressR\bprogress\"\x17\n" +
	"\x15GetTaskRuntimeRequest\"\x8c\x01\n" +
	"\x16GetTaskRuntimeResponse\x128\n" +
	"\frunning_task\x18\x01 \x01(\v2\x15.gitplus.task.v1.TaskR\vrunningTask\x128\n" +
	"\fqueued_tasks\x18\x02 \x03(\v2\x15.gitplus.task.v1.TaskR\vqueuedTasks\"\x18\n" +
	"\x16EnqueueFullSyncRequest\"\x80\x01\n" +
	"\x17EnqueueFullSyncResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\x0e2\".gitplus.task.v1.TaskEnqueueResultR\x06result\x12)\n" +
	"\x04task\x18\x02 \x01(\v2\x15.gitplus.task.v1.TaskR\x04task\"@\n" +
	"\x18EnqueueSourceSyncRequest\x12$\n" +
	"\tsource_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bsourceId\"\x82\x01\n" +
	"\x19EnqueueSourceSyncResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\x0e2\".gitplus.task.v1.TaskEnqueueResultR\x06result\x12)\n" +
	"\x04task\x18\x02 \x01(\v2\x15.gitplus.task.v1.TaskR\x04task\";\n" +
	"\x17CancelQueuedTaskRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06taskId\"E\n" +
	"\x18CancelQueuedTaskResponse\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.gitplus.task.v1.TaskR\x04task\"=\n" +
	"\x16EnqueueTestTaskRequest\x12#\n" +
	"\avariant\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x05(\x01R\avariant\"\x80\x01\n" +
	"\x17EnqueueTestTaskResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\x0e2\".gitplus.task.v1.TaskEnqueueResultR\x06result\x12)\n" +
	"\x04task\x18\x02 \x01(\v2\x15.gitplus.task.v1.TaskR\x04task*V\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_STATE_QUEUED\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x02*\x9a\x01\n" +
	"\x11TaskEnqueueResult\x12#\n" +
	"\x1fTASK_ENQUEUE_RESULT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTASK_ENQUEUE_RESULT_STARTED\x10\x01\x12\x1e\n" +
	"\x1aTASK_ENQUEUE_RESULT_QUEUED\x10\x02\x12\x1f\n" +
	"\x1bTASK_ENQUEUE_RESULT_DEDUPED\x10\x032\x91\x04\n" +
	"\vTaskService\x12a\n" +
	"\x0eGetTaskRuntime\x12&.gitplus.task.v1.GetTaskRuntimeRequest\x1a'.gitplus.task.v1.GetTaskRuntimeResponse\x12d\n" +
	"\x0fEnqueueFullSync\x12'.gitplus.task.v1.EnqueueFullSyncRequest\x1a(.gitplus.task.v1.EnqueueFullSyncResponse\x12j\n" +
	"\x11EnqueueSourceSync\x12).gitplus.task.v1.EnqueueSourceSyncRequest\x1a*.gitplus.task.v1.EnqueueSourceSyncResponse\x12g\n" +
	"\x10CancelQueuedTask\x12(.gitplus.task.v1.CancelQueuedTaskRequest\x1a).gitplus.task.v1.CancelQueuedTaskResponse\x12d\n" +
	"\x0fEnqueueTestTask\x12'.gitplus.task.v1.EnqueueTestTaskRequest\x1a(.gitplus.task.v1.EnqueueTestTaskResponseB\xc5\x01\n" +
	"\x13com.gitplus.task.v1B\tTaskProtoP\x01Z;github.com/ImSingee/git-plus/pkg/rpc/gitplus/task/v1;taskv1\xa2\x02\x03GTX\xaa\x02\x0fGitplus.Task.V1\xca\x02\x0fGitplus\\Task\\V1\xe2\x02\x1bGitplus\\Task\\V1\\GPBMetadata\xea\x02\x11Gitplus::Task::V1\x92\x03\a\xd2>\x02\x10\x01\b\x01b\beditionsp\xe8\a"

var (
	file_gitplus_task_v1_task_proto_rawDescOnce sync.Once
	file_gitplus_task_v1_task_proto_rawDescData []byte
)

func file_gitplus_task_v1_task_proto_rawDescGZIP() []byte {
	file_gitplus_task_v1_task_proto_rawDescOnce.Do(func() {
		file_gitplus_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitplus_task_v1_task_proto_rawDesc), len(file_gitplus_task_v1_task_proto_rawDesc)))
	})
	return file_gitplus_task_v1_task_proto_rawDescData
}

var file_gitplus_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gitplus_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gitplus_task_v1_task_proto_goTypes = []any{
	(TaskState)(0),                    // 0: gitplus.task.v1.TaskState
	(TaskEnqueueResult)(0),            // 1: gitplus.task.v1.TaskEnqueueResult
	(*TaskProgress)(nil),              // 2: gitplus.task.v1.TaskProgress
	(*Task)(nil),                      // 3: gitplus.task.v1.Task
	(*GetTaskRuntimeRequest)(nil),     // 4: gitplus.task.v1.GetTaskRuntimeRequest
	(*GetTaskRuntimeResponse)(nil),    // 5: gitplus.task.v1.GetTaskRuntimeResponse
	(*EnqueueFullSyncRequest)(nil),    // 6: gitplus.task.v1.EnqueueFullSyncRequest
	(*EnqueueFullSyncResponse)(nil),   // 7: gitplus.task.v1.EnqueueFullSyncResponse
	(*EnqueueSourceSyncRequest)(nil),  // 8: gitplus.task.v1.EnqueueSourceSyncRequest
	(*EnqueueSourceSyncResponse)(nil), // 9: gitplus.task.v1.EnqueueSourceSyncResponse
	(*CancelQueuedTaskRequest)(nil),   // 10: gitplus.task.v1.CancelQueuedTaskRequest
	(*CancelQueuedTaskResponse)(nil),  // 11: gitplus.task.v1.CancelQueuedTaskResponse
	(*EnqueueTestTaskRequest)(nil),    // 12: gitplus.task.v1.EnqueueTestTaskRequest
	(*EnqueueTestTaskResponse)(nil),   // 13: gitplus.task.v1.EnqueueTestTaskResponse
	(*structpb.Struct)(nil),           // 14: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_gitplus_task_v1_task_proto_depIdxs = []int32{
	14, // 0: gitplus.task.v1.TaskProgress.meta:type_name -> google.protobuf.Struct
	15, // 1: gitplus.task.v1.TaskProgress.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: gitplus.task.v1.Task.state:type_name -> gitplus.task.v1.TaskState
	15, // 3: gitplus.task.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: gitplus.task.v1.Task.started_at:type_name -> google.protobuf.Timestamp
	2,  // 5: gitplus.task.v1.Task.progress:type_name -> gitplus.task.v1.TaskProgress
	3,  // 6: gitplus.task.v1.GetTaskRuntimeResponse.running_task:type_name -> gitplus.task.v1.Task
	3,  // 7: gitplus.task.v1.GetTaskRuntimeResponse.queued_tasks:type_name -> gitplus.task.v1.Task
	1,  // 8: gitplus.task.v1.EnqueueFullSyncResponse.result:type_name -> gitplus.task.v1.TaskEnqueueResult
	3,  // 9: gitplus.task.v1.EnqueueFullSyncResponse.task:type_name -> gitplus.task.v1.Task
	1,  // 10: gitplus.task.v1.EnqueueSourceSyncResponse.result:type_name -> gitplus.task.v1.TaskEnqueueResult
	3,  // 11: gitplus.task.v1.EnqueueSourceSyncResponse.task:type_name -> gitplus.task.v1.Task
	3,  // 12: gitplus.task.v1.CancelQueuedTaskResponse.task:type_name -> gitplus.task.v1.Task
	1,  // 13: gitplus.task.v1.EnqueueTestTaskResponse.result:type_name -> gitplus.task.v1.TaskEnqueueResult
	3,  // 14: gitplus.task.v1.EnqueueTestTaskResponse.task:type_name -> gitplus.task.v1.Task
	4,  // 15: gitplus.task.v1.TaskService.GetTaskRuntime:input_type -> gitplus.task.v1.GetTaskRuntimeRequest
	6,  // 16: gitplus.task.v1.TaskService.EnqueueFullSync:input_type -> gitplus.task.v1.EnqueueFullSyncRequest
	8,  // 17: gitplus.task.v1.TaskService.EnqueueSourceSync:input_type -> gitplus.task.v1.EnqueueSourceSyncRequest
	10, // 18: gitplus.task.v1.TaskService.CancelQueuedTask:input_type -> gitplus.task.v1.CancelQueuedTaskRequest
	12, // 19: gitplus.task.v1.TaskService.EnqueueTestTask:input_type -> gitplus.task.v1.EnqueueTestTaskRequest
	5,  // 20: gitplus.task.v1.TaskService.GetTaskRuntime:output_type -> gitplus.task.v1.GetTaskRuntimeResponse
	7,  // 21: gitplus.task.v1.TaskService.EnqueueFullSync:output_type -> gitplus.task.v1.EnqueueFullSyncResponse
	9,  // 22: gitplus.task.v1.TaskService.EnqueueSourceSync:output_type -> gitplus.task.v1.EnqueueSourceSyncResponse
	11, // 23: gitplus.task.v1.TaskService.CancelQueuedTask:output_type -> gitplus.task.v1.CancelQueuedTaskResponse
	13, // 24: gitplus.task.v1.TaskService.EnqueueTestTask:output_type -> gitplus.task.v1.EnqueueTestTaskResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gitplus_task_v1_task_proto_init() }
func file_gitplus_task_v1_task_proto_init() {
	if File_gitplus_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitplus_task_v1_task_proto_rawDesc), len(file_gitplus_task_v1_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitplus_task_v1_task_proto_goTypes,
		DependencyIndexes: file_gitplus_task_v1_task_proto_depIdxs,
		EnumInfos:         file_gitplus_task_v1_task_proto_enumTypes,
		MessageInfos:      file_gitplus_task_v1_task_proto_msgTypes,
	}.Build()
	File_gitplus_task_v1_task_proto = out.File
	file_gitplus_task_v1_task_proto_goTypes = nil
	file_gitplus_task_v1_task_proto_depIdxs = nil
}
