// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitplus/event/v1/event.proto

package eventv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *string                `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_gitplus_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gitplus_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *structpb.Struct       `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_gitplus_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitplus_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_gitplus_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetEvent() *structpb.Struct {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_gitplus_event_v1_event_proto protoreflect.FileDescriptor

const file_gitplus_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1cgitplus/event/v1/event.proto\x12\x10gitplus.event.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\"5\n" +
	"\x10SubscribeRequest\x12!\n" +
	"\achannel\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\achannel\"B\n" +
	"\x11SubscribeResponse\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05event2f\n" +
	"\fEventService\x12V\n" +
	"\tSubscribe\x12\".gitplus.event.v1.SubscribeRequest\x1a#.gitplus.event.v1.SubscribeResponse0\x01B\xcd\x01\n" +
	"\x14com.gitplus.event.v1B\n" +
	"EventProtoP\x01Z=github.com/ImSingee/git-plus/pkg/rpc/gitplus/event/v1;eventv1\xa2\x02\x03GEX\xaa\x02\x10Gitplus.Event.V1\xca\x02\x10Gitplus\\Event\\V1\xe2\x02\x1cGitplus\\Event\\V1\\GPBMetadata\xea\x02\x12Gitplus::Event::V1\x92\x03\a\xd2>\x02\x10\x01\b\x01b\beditionsp\xe8\a"

var (
	file_gitplus_event_v1_event_proto_rawDescOnce sync.Once
	file_gitplus_event_v1_event_proto_rawDescData []byte
)

func file_gitplus_event_v1_event_proto_rawDescGZIP() []byte {
	file_gitplus_event_v1_event_proto_rawDescOnce.Do(func() {
		file_gitplus_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitplus_event_v1_event_proto_rawDesc), len(file_gitplus_event_v1_event_proto_rawDesc)))
	})
	return file_gitplus_event_v1_event_proto_rawDescData
}

var file_gitplus_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gitplus_event_v1_event_proto_goTypes = []any{
	(*SubscribeRequest)(nil),  // 0: gitplus.event.v1.SubscribeRequest
	(*SubscribeResponse)(nil), // 1: gitplus.event.v1.SubscribeResponse
	(*structpb.Struct)(nil),   // 2: google.protobuf.Struct
}
var file_gitplus_event_v1_event_proto_depIdxs = []int32{
	2, // 0: gitplus.event.v1.SubscribeResponse.event:type_name -> google.protobuf.Struct
	0, // 1: gitplus.event.v1.EventService.Subscribe:input_type -> gitplus.event.v1.SubscribeRequest
	1, // 2: gitplus.event.v1.EventService.Subscribe:output_type -> gitplus.event.v1.SubscribeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gitplus_event_v1_event_proto_init() }
func file_gitplus_event_v1_event_proto_init() {
	if File_gitplus_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitplus_event_v1_event_proto_rawDesc), len(file_gitplus_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitplus_event_v1_event_proto_goTypes,
		DependencyIndexes: file_gitplus_event_v1_event_proto_depIdxs,
		MessageInfos:      file_gitplus_event_v1_event_proto_msgTypes,
	}.Build()
	File_gitplus_event_v1_event_proto = out.File
	file_gitplus_event_v1_event_proto_goTypes = nil
	file_gitplus_event_v1_event_proto_depIdxs = nil
}
