/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as R404RouteImport } from './routes/404'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardReposRouteImport } from './routes/_dashboard/repos'
import { Route as DashboardMaintenanceRouteImport } from './routes/_dashboard/maintenance'
import { Route as DashboardConfigRouteImport } from './routes/_dashboard/config'
import { Route as DashboardMaintenanceIndexRouteImport } from './routes/_dashboard/maintenance/index'
import { Route as DashboardConfigIndexRouteImport } from './routes/_dashboard/config/index'
import { Route as DashboardConfigSourcesRouteImport } from './routes/_dashboard/config/sources'
import { Route as DashboardConfigCronRouteImport } from './routes/_dashboard/config/cron'
import { Route as DashboardMaintenanceTasksIndexRouteImport } from './routes/_dashboard/maintenance/tasks.index'
import { Route as DashboardMaintenanceTasksTaskIdRouteImport } from './routes/_dashboard/maintenance/tasks.$taskId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReposRoute = DashboardReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaintenanceIndexRoute =
  DashboardMaintenanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMaintenanceRoute,
  } as any)
const DashboardConfigIndexRoute = DashboardConfigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardConfigRoute,
} as any)
const DashboardConfigSourcesRoute = DashboardConfigSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardConfigRoute,
} as any)
const DashboardConfigCronRoute = DashboardConfigCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => DashboardConfigRoute,
} as any)
const DashboardMaintenanceTasksIndexRoute =
  DashboardMaintenanceTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => DashboardMaintenanceRoute,
  } as any)
const DashboardMaintenanceTasksTaskIdRoute =
  DashboardMaintenanceTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => DashboardMaintenanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof DashboardIndexRoute
  '/config': typeof DashboardConfigRouteWithChildren
  '/maintenance': typeof DashboardMaintenanceRouteWithChildren
  '/repos': typeof DashboardReposRoute
  '/config/cron': typeof DashboardConfigCronRoute
  '/config/sources': typeof DashboardConfigSourcesRoute
  '/config/': typeof DashboardConfigIndexRoute
  '/maintenance/': typeof DashboardMaintenanceIndexRoute
  '/maintenance/tasks/$taskId': typeof DashboardMaintenanceTasksTaskIdRoute
  '/maintenance/tasks/': typeof DashboardMaintenanceTasksIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/repos': typeof DashboardReposRoute
  '/': typeof DashboardIndexRoute
  '/config/cron': typeof DashboardConfigCronRoute
  '/config/sources': typeof DashboardConfigSourcesRoute
  '/config': typeof DashboardConfigIndexRoute
  '/maintenance': typeof DashboardMaintenanceIndexRoute
  '/maintenance/tasks/$taskId': typeof DashboardMaintenanceTasksTaskIdRoute
  '/maintenance/tasks': typeof DashboardMaintenanceTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/config': typeof DashboardConfigRouteWithChildren
  '/_dashboard/maintenance': typeof DashboardMaintenanceRouteWithChildren
  '/_dashboard/repos': typeof DashboardReposRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/config/cron': typeof DashboardConfigCronRoute
  '/_dashboard/config/sources': typeof DashboardConfigSourcesRoute
  '/_dashboard/config/': typeof DashboardConfigIndexRoute
  '/_dashboard/maintenance/': typeof DashboardMaintenanceIndexRoute
  '/_dashboard/maintenance/tasks/$taskId': typeof DashboardMaintenanceTasksTaskIdRoute
  '/_dashboard/maintenance/tasks/': typeof DashboardMaintenanceTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/config'
    | '/maintenance'
    | '/repos'
    | '/config/cron'
    | '/config/sources'
    | '/config/'
    | '/maintenance/'
    | '/maintenance/tasks/$taskId'
    | '/maintenance/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/repos'
    | '/'
    | '/config/cron'
    | '/config/sources'
    | '/config'
    | '/maintenance'
    | '/maintenance/tasks/$taskId'
    | '/maintenance/tasks'
  id:
    | '__root__'
    | '/404'
    | '/_dashboard'
    | '/_dashboard/config'
    | '/_dashboard/maintenance'
    | '/_dashboard/repos'
    | '/_dashboard/'
    | '/_dashboard/config/cron'
    | '/_dashboard/config/sources'
    | '/_dashboard/config/'
    | '/_dashboard/maintenance/'
    | '/_dashboard/maintenance/tasks/$taskId'
    | '/_dashboard/maintenance/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/repos': {
      id: '/_dashboard/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof DashboardReposRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/maintenance': {
      id: '/_dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/config': {
      id: '/_dashboard/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/maintenance/': {
      id: '/_dashboard/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof DashboardMaintenanceIndexRouteImport
      parentRoute: typeof DashboardMaintenanceRoute
    }
    '/_dashboard/config/': {
      id: '/_dashboard/config/'
      path: '/'
      fullPath: '/config/'
      preLoaderRoute: typeof DashboardConfigIndexRouteImport
      parentRoute: typeof DashboardConfigRoute
    }
    '/_dashboard/config/sources': {
      id: '/_dashboard/config/sources'
      path: '/sources'
      fullPath: '/config/sources'
      preLoaderRoute: typeof DashboardConfigSourcesRouteImport
      parentRoute: typeof DashboardConfigRoute
    }
    '/_dashboard/config/cron': {
      id: '/_dashboard/config/cron'
      path: '/cron'
      fullPath: '/config/cron'
      preLoaderRoute: typeof DashboardConfigCronRouteImport
      parentRoute: typeof DashboardConfigRoute
    }
    '/_dashboard/maintenance/tasks/': {
      id: '/_dashboard/maintenance/tasks/'
      path: '/tasks'
      fullPath: '/maintenance/tasks/'
      preLoaderRoute: typeof DashboardMaintenanceTasksIndexRouteImport
      parentRoute: typeof DashboardMaintenanceRoute
    }
    '/_dashboard/maintenance/tasks/$taskId': {
      id: '/_dashboard/maintenance/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/maintenance/tasks/$taskId'
      preLoaderRoute: typeof DashboardMaintenanceTasksTaskIdRouteImport
      parentRoute: typeof DashboardMaintenanceRoute
    }
  }
}

interface DashboardConfigRouteChildren {
  DashboardConfigCronRoute: typeof DashboardConfigCronRoute
  DashboardConfigSourcesRoute: typeof DashboardConfigSourcesRoute
  DashboardConfigIndexRoute: typeof DashboardConfigIndexRoute
}

const DashboardConfigRouteChildren: DashboardConfigRouteChildren = {
  DashboardConfigCronRoute: DashboardConfigCronRoute,
  DashboardConfigSourcesRoute: DashboardConfigSourcesRoute,
  DashboardConfigIndexRoute: DashboardConfigIndexRoute,
}

const DashboardConfigRouteWithChildren = DashboardConfigRoute._addFileChildren(
  DashboardConfigRouteChildren,
)

interface DashboardMaintenanceRouteChildren {
  DashboardMaintenanceIndexRoute: typeof DashboardMaintenanceIndexRoute
  DashboardMaintenanceTasksTaskIdRoute: typeof DashboardMaintenanceTasksTaskIdRoute
  DashboardMaintenanceTasksIndexRoute: typeof DashboardMaintenanceTasksIndexRoute
}

const DashboardMaintenanceRouteChildren: DashboardMaintenanceRouteChildren = {
  DashboardMaintenanceIndexRoute: DashboardMaintenanceIndexRoute,
  DashboardMaintenanceTasksTaskIdRoute: DashboardMaintenanceTasksTaskIdRoute,
  DashboardMaintenanceTasksIndexRoute: DashboardMaintenanceTasksIndexRoute,
}

const DashboardMaintenanceRouteWithChildren =
  DashboardMaintenanceRoute._addFileChildren(DashboardMaintenanceRouteChildren)

interface DashboardRouteChildren {
  DashboardConfigRoute: typeof DashboardConfigRouteWithChildren
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRouteWithChildren
  DashboardReposRoute: typeof DashboardReposRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfigRoute: DashboardConfigRouteWithChildren,
  DashboardMaintenanceRoute: DashboardMaintenanceRouteWithChildren,
  DashboardReposRoute: DashboardReposRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
