// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitplus/repo/v1/repo.proto (package gitplus.repo.v1, edition 2023)
// option features.field_presence = EXPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_go_features, file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file gitplus/repo/v1/repo.proto.
 */
export const file_gitplus_repo_v1_repo: GenFile = /*@__PURE__*/
  fileDesc("ChpnaXRwbHVzL3JlcG8vdjEvcmVwby5wcm90bxIPZ2l0cGx1cy5yZXBvLnYxIucDCgpSZXBvc2l0b3J5EgoKAmlkGAEgASgDEhEKCXNvdXJjZV9pZBgCIAEoCRIQCghwbGF0Zm9ybRgDIAEoCRIMCgRuYW1lGAQgASgJEhEKCWZ1bGxfbmFtZRgFIAEoCRINCgVvd25lchgGIAEoCRITCgtkZXNjcmlwdGlvbhgHIAEoCRIQCghodG1sX3VybBgIIAEoCRIRCgljbG9uZV91cmwYCSABKAkSDwoHc3NoX3VybBgKIAEoCRIWCg5kZWZhdWx0X2JyYW5jaBgLIAEoCRISCgp2aXNpYmlsaXR5GAwgASgJEhIKCmlzX3ByaXZhdGUYDSABKAgSDwoHaXNfZm9yaxgOIAEoCBITCgtpc19hcmNoaXZlZBgPIAEoCBIOCgZzdGF0dXMYECABKAkSMAoMbGFzdF9zZWVuX2F0GBEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgpjcmVhdGVkX2F0GBIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GBMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIlCgRtZXRhGBQgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdCJ8ChdMaXN0UmVwb3NpdG9yaWVzUmVxdWVzdBIcCglwYWdlX3NpemUYASABKAVCCbpIBhoEGGQoARISCgpwYWdlX3Rva2VuGAIgASgJEg4KBnNlYXJjaBgDIAEoCRIRCglzb3VyY2VfaWQYBCABKAkSDAoEc29ydBgFIAEoCSJ7ChhMaXN0UmVwb3NpdG9yaWVzUmVzcG9uc2USMQoMcmVwb3NpdG9yaWVzGAEgAygLMhsuZ2l0cGx1cy5yZXBvLnYxLlJlcG9zaXRvcnkSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJEhMKC3RvdGFsX2NvdW50GAMgASgFMnYKC1JlcG9TZXJ2aWNlEmcKEExpc3RSZXBvc2l0b3JpZXMSKC5naXRwbHVzLnJlcG8udjEuTGlzdFJlcG9zaXRvcmllc1JlcXVlc3QaKS5naXRwbHVzLnJlcG8udjEuTGlzdFJlcG9zaXRvcmllc1Jlc3BvbnNlQsUBChNjb20uZ2l0cGx1cy5yZXBvLnYxQglSZXBvUHJvdG9QAVo7Z2l0aHViLmNvbS9JbVNpbmdlZS9naXQtcGx1cy9wa2cvcnBjL2dpdHBsdXMvcmVwby92MTtyZXBvdjGiAgNHUliqAg9HaXRwbHVzLlJlcG8uVjHKAg9HaXRwbHVzXFJlcG9cVjHiAhtHaXRwbHVzXFJlcG9cVjFcR1BCTWV0YWRhdGHqAhFHaXRwbHVzOjpSZXBvOjpWMZIDBwgB0j4CEAFiCGVkaXRpb25zcOgH", [file_buf_validate_validate, file_google_protobuf_go_features, file_google_protobuf_struct, file_google_protobuf_timestamp]);

/**
 * @generated from message gitplus.repo.v1.Repository
 */
export type Repository = Message<"gitplus.repo.v1.Repository"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string source_id = 2;
   */
  sourceId: string;

  /**
   * @generated from field: string platform = 3;
   */
  platform: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string full_name = 5;
   */
  fullName: string;

  /**
   * @generated from field: string owner = 6;
   */
  owner: string;

  /**
   * @generated from field: string description = 7;
   */
  description: string;

  /**
   * @generated from field: string html_url = 8;
   */
  htmlUrl: string;

  /**
   * @generated from field: string clone_url = 9;
   */
  cloneUrl: string;

  /**
   * @generated from field: string ssh_url = 10;
   */
  sshUrl: string;

  /**
   * @generated from field: string default_branch = 11;
   */
  defaultBranch: string;

  /**
   * @generated from field: string visibility = 12;
   */
  visibility: string;

  /**
   * @generated from field: bool is_private = 13;
   */
  isPrivate: boolean;

  /**
   * @generated from field: bool is_fork = 14;
   */
  isFork: boolean;

  /**
   * @generated from field: bool is_archived = 15;
   */
  isArchived: boolean;

  /**
   * @generated from field: string status = 16;
   */
  status: string;

  /**
   * @generated from field: google.protobuf.Timestamp last_seen_at = 17;
   */
  lastSeenAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 18;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 19;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Struct meta = 20;
   */
  meta?: JsonObject;
};

/**
 * Describes the message gitplus.repo.v1.Repository.
 * Use `create(RepositorySchema)` to create a new message.
 */
export const RepositorySchema: GenMessage<Repository> = /*@__PURE__*/
  messageDesc(file_gitplus_repo_v1_repo, 0);

/**
 * @generated from message gitplus.repo.v1.ListRepositoriesRequest
 */
export type ListRepositoriesRequest = Message<"gitplus.repo.v1.ListRepositoriesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;

  /**
   * @generated from field: string search = 3;
   */
  search: string;

  /**
   * @generated from field: string source_id = 4;
   */
  sourceId: string;

  /**
   * Sort key combining field and direction.
   * Accepted values: "created_at_desc" (default), "created_at_asc",
   * "full_name_asc", "full_name_desc".
   *
   * @generated from field: string sort = 5;
   */
  sort: string;
};

/**
 * Describes the message gitplus.repo.v1.ListRepositoriesRequest.
 * Use `create(ListRepositoriesRequestSchema)` to create a new message.
 */
export const ListRepositoriesRequestSchema: GenMessage<ListRepositoriesRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_repo_v1_repo, 1);

/**
 * @generated from message gitplus.repo.v1.ListRepositoriesResponse
 */
export type ListRepositoriesResponse = Message<"gitplus.repo.v1.ListRepositoriesResponse"> & {
  /**
   * @generated from field: repeated gitplus.repo.v1.Repository repositories = 1;
   */
  repositories: Repository[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message gitplus.repo.v1.ListRepositoriesResponse.
 * Use `create(ListRepositoriesResponseSchema)` to create a new message.
 */
export const ListRepositoriesResponseSchema: GenMessage<ListRepositoriesResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_repo_v1_repo, 2);

/**
 * @generated from service gitplus.repo.v1.RepoService
 */
export const RepoService: GenService<{
  /**
   * @generated from rpc gitplus.repo.v1.RepoService.ListRepositories
   */
  listRepositories: {
    methodKind: "unary";
    input: typeof ListRepositoriesRequestSchema;
    output: typeof ListRepositoriesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gitplus_repo_v1_repo, 0);

