// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitplus/config/v1/config.proto (package gitplus.config.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gitplus/config/v1/config.proto.
 */
export const file_gitplus_config_v1_config: GenFile = /*@__PURE__*/
  fileDesc("Ch5naXRwbHVzL2NvbmZpZy92MS9jb25maWcucHJvdG8SEWdpdHBsdXMuY29uZmlnLnYxIoECCg9WYWxpZGF0aW9uSXNzdWUSPQoIc2V2ZXJpdHkYASABKA4yKy5naXRwbHVzLmNvbmZpZy52MS5WYWxpZGF0aW9uSXNzdWUuU2V2ZXJpdHkSDAoEY29kZRgCIAEoCRIPCgdtZXNzYWdlGAMgASgJEgwKBHBhdGgYBCABKAkSEQoJc291cmNlX2lkGAUgASgJEgwKBGxpbmUYBiABKAUiYQoIU2V2ZXJpdHkSGAoUU0VWRVJJVFlfVU5TUEVDSUZJRUQQABISCg5TRVZFUklUWV9FUlJPUhABEhQKEFNFVkVSSVRZX1dBUk5JTkcQAhIRCg1TRVZFUklUWV9JTkZPEAMiPAoMSXNzdWVTdW1tYXJ5Eg0KBWVycm9yGAEgASgFEg8KB3dhcm5pbmcYAiABKAUSDAoEaW5mbxgDIAEoBSIUChJDaGVja0NvbmZpZ1JlcXVlc3QimQEKE0NoZWNrQ29uZmlnUmVzcG9uc2USDAoEcGF0aBgBIAEoCRIOCgZleGlzdHMYAiABKAgSMgoGaXNzdWVzGAMgAygLMiIuZ2l0cGx1cy5jb25maWcudjEuVmFsaWRhdGlvbklzc3VlEjAKB3N1bW1hcnkYBCABKAsyHy5naXRwbHVzLmNvbmZpZy52MS5Jc3N1ZVN1bW1hcnkiLQoYQ2hlY2tTb3VyY2VDb25maWdSZXF1ZXN0EhEKCXNvdXJjZV9pZBgBIAEoCSKyAQoZQ2hlY2tTb3VyY2VDb25maWdSZXNwb25zZRIMCgRwYXRoGAEgASgJEg4KBmV4aXN0cxgCIAEoCBIRCglzb3VyY2VfaWQYAyABKAkSMgoGaXNzdWVzGAQgAygLMiIuZ2l0cGx1cy5jb25maWcudjEuVmFsaWRhdGlvbklzc3VlEjAKB3N1bW1hcnkYBSABKAsyHy5naXRwbHVzLmNvbmZpZy52MS5Jc3N1ZVN1bW1hcnky3QEKDUNvbmZpZ1NlcnZpY2USXAoLQ2hlY2tDb25maWcSJS5naXRwbHVzLmNvbmZpZy52MS5DaGVja0NvbmZpZ1JlcXVlc3QaJi5naXRwbHVzLmNvbmZpZy52MS5DaGVja0NvbmZpZ1Jlc3BvbnNlEm4KEUNoZWNrU291cmNlQ29uZmlnEisuZ2l0cGx1cy5jb25maWcudjEuQ2hlY2tTb3VyY2VDb25maWdSZXF1ZXN0GiwuZ2l0cGx1cy5jb25maWcudjEuQ2hlY2tTb3VyY2VDb25maWdSZXNwb25zZULHAQoVY29tLmdpdHBsdXMuY29uZmlnLnYxQgtDb25maWdQcm90b1ABWjtnaXRodWIuY29tL0ltU2luZ2VlL2dpdC1wbHVzL3JwYy9naXRwbHVzL2NvbmZpZy92MTtjb25maWd2MaICA0dDWKoCEUdpdHBsdXMuQ29uZmlnLlYxygIRR2l0cGx1c1xDb25maWdcVjHiAh1HaXRwbHVzXENvbmZpZ1xWMVxHUEJNZXRhZGF0YeoCE0dpdHBsdXM6OkNvbmZpZzo6VjFiBnByb3RvMw");

/**
 * @generated from message gitplus.config.v1.ValidationIssue
 */
export type ValidationIssue = Message<"gitplus.config.v1.ValidationIssue"> & {
  /**
   * @generated from field: gitplus.config.v1.ValidationIssue.Severity severity = 1;
   */
  severity: ValidationIssue_Severity;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * @generated from field: string path = 4;
   */
  path: string;

  /**
   * @generated from field: string source_id = 5;
   */
  sourceId: string;

  /**
   * @generated from field: int32 line = 6;
   */
  line: number;
};

/**
 * Describes the message gitplus.config.v1.ValidationIssue.
 * Use `create(ValidationIssueSchema)` to create a new message.
 */
export const ValidationIssueSchema: GenMessage<ValidationIssue> = /*@__PURE__*/
  messageDesc(file_gitplus_config_v1_config, 0);

/**
 * @generated from enum gitplus.config.v1.ValidationIssue.Severity
 */
export enum ValidationIssue_Severity {
  /**
   * @generated from enum value: SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEVERITY_ERROR = 1;
   */
  ERROR = 1,

  /**
   * @generated from enum value: SEVERITY_WARNING = 2;
   */
  WARNING = 2,

  /**
   * @generated from enum value: SEVERITY_INFO = 3;
   */
  INFO = 3,
}

/**
 * Describes the enum gitplus.config.v1.ValidationIssue.Severity.
 */
export const ValidationIssue_SeveritySchema: GenEnum<ValidationIssue_Severity> = /*@__PURE__*/
  enumDesc(file_gitplus_config_v1_config, 0, 0);

/**
 * @generated from message gitplus.config.v1.IssueSummary
 */
export type IssueSummary = Message<"gitplus.config.v1.IssueSummary"> & {
  /**
   * @generated from field: int32 error = 1;
   */
  error: number;

  /**
   * @generated from field: int32 warning = 2;
   */
  warning: number;

  /**
   * @generated from field: int32 info = 3;
   */
  info: number;
};

/**
 * Describes the message gitplus.config.v1.IssueSummary.
 * Use `create(IssueSummarySchema)` to create a new message.
 */
export const IssueSummarySchema: GenMessage<IssueSummary> = /*@__PURE__*/
  messageDesc(file_gitplus_config_v1_config, 1);

/**
 * @generated from message gitplus.config.v1.CheckConfigRequest
 */
export type CheckConfigRequest = Message<"gitplus.config.v1.CheckConfigRequest"> & {
};

/**
 * Describes the message gitplus.config.v1.CheckConfigRequest.
 * Use `create(CheckConfigRequestSchema)` to create a new message.
 */
export const CheckConfigRequestSchema: GenMessage<CheckConfigRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_config_v1_config, 2);

/**
 * @generated from message gitplus.config.v1.CheckConfigResponse
 */
export type CheckConfigResponse = Message<"gitplus.config.v1.CheckConfigResponse"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: bool exists = 2;
   */
  exists: boolean;

  /**
   * @generated from field: repeated gitplus.config.v1.ValidationIssue issues = 3;
   */
  issues: ValidationIssue[];

  /**
   * @generated from field: gitplus.config.v1.IssueSummary summary = 4;
   */
  summary?: IssueSummary;
};

/**
 * Describes the message gitplus.config.v1.CheckConfigResponse.
 * Use `create(CheckConfigResponseSchema)` to create a new message.
 */
export const CheckConfigResponseSchema: GenMessage<CheckConfigResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_config_v1_config, 3);

/**
 * @generated from message gitplus.config.v1.CheckSourceConfigRequest
 */
export type CheckSourceConfigRequest = Message<"gitplus.config.v1.CheckSourceConfigRequest"> & {
  /**
   * @generated from field: string source_id = 1;
   */
  sourceId: string;
};

/**
 * Describes the message gitplus.config.v1.CheckSourceConfigRequest.
 * Use `create(CheckSourceConfigRequestSchema)` to create a new message.
 */
export const CheckSourceConfigRequestSchema: GenMessage<CheckSourceConfigRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_config_v1_config, 4);

/**
 * @generated from message gitplus.config.v1.CheckSourceConfigResponse
 */
export type CheckSourceConfigResponse = Message<"gitplus.config.v1.CheckSourceConfigResponse"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: bool exists = 2;
   */
  exists: boolean;

  /**
   * @generated from field: string source_id = 3;
   */
  sourceId: string;

  /**
   * @generated from field: repeated gitplus.config.v1.ValidationIssue issues = 4;
   */
  issues: ValidationIssue[];

  /**
   * @generated from field: gitplus.config.v1.IssueSummary summary = 5;
   */
  summary?: IssueSummary;
};

/**
 * Describes the message gitplus.config.v1.CheckSourceConfigResponse.
 * Use `create(CheckSourceConfigResponseSchema)` to create a new message.
 */
export const CheckSourceConfigResponseSchema: GenMessage<CheckSourceConfigResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_config_v1_config, 5);

/**
 * @generated from service gitplus.config.v1.ConfigService
 */
export const ConfigService: GenService<{
  /**
   * @generated from rpc gitplus.config.v1.ConfigService.CheckConfig
   */
  checkConfig: {
    methodKind: "unary";
    input: typeof CheckConfigRequestSchema;
    output: typeof CheckConfigResponseSchema;
  },
  /**
   * @generated from rpc gitplus.config.v1.ConfigService.CheckSourceConfig
   */
  checkSourceConfig: {
    methodKind: "unary";
    input: typeof CheckSourceConfigRequestSchema;
    output: typeof CheckSourceConfigResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gitplus_config_v1_config, 0);

