// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitplus/event/v1/event.proto (package gitplus.event.v1, edition 2023)
// option features.field_presence = EXPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_protobuf_go_features, file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file gitplus/event/v1/event.proto.
 */
export const file_gitplus_event_v1_event: GenFile = /*@__PURE__*/
  fileDesc("ChxnaXRwbHVzL2V2ZW50L3YxL2V2ZW50LnByb3RvEhBnaXRwbHVzLmV2ZW50LnYxIiwKEFN1YnNjcmliZVJlcXVlc3QSGAoHY2hhbm5lbBgBIAEoCUIHukgEcgIQASI7ChFTdWJzY3JpYmVSZXNwb25zZRImCgVldmVudBgBIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QyZgoMRXZlbnRTZXJ2aWNlElYKCVN1YnNjcmliZRIiLmdpdHBsdXMuZXZlbnQudjEuU3Vic2NyaWJlUmVxdWVzdBojLmdpdHBsdXMuZXZlbnQudjEuU3Vic2NyaWJlUmVzcG9uc2UwAULNAQoUY29tLmdpdHBsdXMuZXZlbnQudjFCCkV2ZW50UHJvdG9QAVo9Z2l0aHViLmNvbS9JbVNpbmdlZS9naXQtcGx1cy9wa2cvcnBjL2dpdHBsdXMvZXZlbnQvdjE7ZXZlbnR2MaICA0dFWKoCEEdpdHBsdXMuRXZlbnQuVjHKAhBHaXRwbHVzXEV2ZW50XFYx4gIcR2l0cGx1c1xFdmVudFxWMVxHUEJNZXRhZGF0YeoCEkdpdHBsdXM6OkV2ZW50OjpWMZIDBwgB0j4CEAFiCGVkaXRpb25zcOgH", [file_buf_validate_validate, file_google_protobuf_go_features, file_google_protobuf_struct]);

/**
 * @generated from message gitplus.event.v1.SubscribeRequest
 */
export type SubscribeRequest = Message<"gitplus.event.v1.SubscribeRequest"> & {
  /**
   * @generated from field: string channel = 1;
   */
  channel: string;
};

/**
 * Describes the message gitplus.event.v1.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> = /*@__PURE__*/
  messageDesc(file_gitplus_event_v1_event, 0);

/**
 * @generated from message gitplus.event.v1.SubscribeResponse
 */
export type SubscribeResponse = Message<"gitplus.event.v1.SubscribeResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct event = 1;
   */
  event?: JsonObject;
};

/**
 * Describes the message gitplus.event.v1.SubscribeResponse.
 * Use `create(SubscribeResponseSchema)` to create a new message.
 */
export const SubscribeResponseSchema: GenMessage<SubscribeResponse> = /*@__PURE__*/
  messageDesc(file_gitplus_event_v1_event, 1);

/**
 * @generated from service gitplus.event.v1.EventService
 */
export const EventService: GenService<{
  /**
   * @generated from rpc gitplus.event.v1.EventService.Subscribe
   */
  subscribe: {
    methodKind: "server_streaming";
    input: typeof SubscribeRequestSchema;
    output: typeof SubscribeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_gitplus_event_v1_event, 0);

